//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.MtEnhancedProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.MtEnhancedProvider.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key has been set.  Please open the plugin settings form and enter a valid API key.
        /// </summary>
        public static string ApiConnectionGoogleNoKeyErrorMessage {
            get {
                return ResourceManager.GetString("ApiConnectionGoogleNoKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem getting the translation..
        /// </summary>
        public static string ApiConnectorGoogleAuthErrorMsg1 {
            get {
                return ResourceManager.GetString("ApiConnectorGoogleAuthErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that you have entered the correct API key and that your language pair is supported..
        /// </summary>
        public static string ApiConnectorGoogleAuthErrorMsg2 {
            get {
                return ResourceManager.GetString("ApiConnectorGoogleAuthErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add API key..
        /// </summary>
        public static string ApiKeyError {
            get {
                return ResourceManager.GetString("ApiKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTEnhanced.
        /// </summary>
        public static string AppLogFolder {
            get {
                return ResourceManager.GetString("AppLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Provider.
        /// </summary>
        public static string BackBtnText {
            get {
                return ResourceManager.GetString("BackBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backImg {
            get {
                object obj = ResourceManager.GetObject("backImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseBtn {
            get {
                return ResourceManager.GetString("BrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Category Id.
        /// </summary>
        public static string CatIdDescription {
            get {
                return ResourceManager.GetString("CatIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add Category Id otherwise uncheck CategoryId checbox..
        /// </summary>
        public static string CatIdError {
            get {
                return ResourceManager.GetString("CatIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings error.
        /// </summary>
        public static string EditSettingsErrorCaption {
            get {
                return ResourceManager.GetString("EditSettingsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with edit settings:.
        /// </summary>
        public static string EditSettingsGenericErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation..
        /// </summary>
        public static string EditSettingsXmlErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsXmlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local path to json file cannot be empty..
        /// </summary>
        public static string EmptyJsonFilePathMsg {
            get {
                return ResourceManager.GetString("EmptyJsonFilePathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty..
        /// </summary>
        public static string EmptyProjectNameMsd {
            get {
                return ResourceManager.GetString("EmptyProjectNameMsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ForumIcon {
            get {
                object obj = ResourceManager.GetObject("ForumIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translator.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Google Translate.
        /// </summary>
        public static string Google_Description {
            get {
                return ResourceManager.GetString("Google_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Google Translate.
        /// </summary>
        public static string Google_Name {
            get {
                return ResourceManager.GetString("Google_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Google Translate.
        /// </summary>
        public static string Google_NiceName {
            get {
                return ResourceManager.GetString("Google_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Google Translate.
        /// </summary>
        public static string Google_Tooltip {
            get {
                return ResourceManager.GetString("Google_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Google Translate Advanced.
        /// </summary>
        public static string GoogleAdvanced {
            get {
                return ResourceManager.GetString("GoogleAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the version of the Google Translate API that you wish to use:.
        /// </summary>
        public static string GoogleApiDescription {
            get {
                return ResourceManager.GetString("GoogleApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOGLE_APPLICATION_CREDENTIALS.
        /// </summary>
        public static string GoogleApiEnvironmentVariableName {
            get {
                return ResourceManager.GetString("GoogleApiEnvironmentVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Google Translate API Key.
        /// </summary>
        public static string GoogleApiKeyDescription {
            get {
                return ResourceManager.GetString("GoogleApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2 - Basic Translation.
        /// </summary>
        public static string GoogleApiVersionV2Description {
            get {
                return ResourceManager.GetString("GoogleApiVersionV2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3 - Advanced Translation.
        /// </summary>
        public static string GoogleApiVersionV3Description {
            get {
                return ResourceManager.GetString("GoogleApiVersionV3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Google Translate Basic.
        /// </summary>
        public static string GoogleBasic {
            get {
                return ResourceManager.GetString("GoogleBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter AutoML Translation model:.
        /// </summary>
        public static string GoogleEngineModelDescription {
            get {
                return ResourceManager.GetString("GoogleEngineModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model name.
        /// </summary>
        public static string GoogleInvalidEngine {
            get {
                return ResourceManager.GetString("GoogleInvalidEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add project location:.
        /// </summary>
        public static string GoogleProjectLocation {
            get {
                return ResourceManager.GetString("GoogleProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Response.
        /// </summary>
        public static string GoogleResponseDescription {
            get {
                return ResourceManager.GetString("GoogleResponseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name..
        /// </summary>
        public static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem checking language pair support..
        /// </summary>
        public static string LangPairAuthErrorMsg1 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that you have entered the correct API key..
        /// </summary>
        public static string LangPairAuthErrorMsg2 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, close/reopen the current dialog and try again.
        /// </summary>
        public static string LangPairAuthErrorMsg3 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTEnhancedLogs.txt.
        /// </summary>
        public static string LogsFileName {
            get {
                return ResourceManager.GetString("LogsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWS AppStore.
        /// </summary>
        public static string LogsFolderPath {
            get {
                return ResourceManager.GetString("LogsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_Description {
            get {
                return ResourceManager.GetString("Microsoft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap microsoft_image {
            get {
                object obj = ResourceManager.GetObject("microsoft_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_Name {
            get {
                return ResourceManager.GetString("Microsoft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_NiceName {
            get {
                return ResourceManager.GetString("Microsoft_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_Tooltip {
            get {
                return ResourceManager.GetString("Microsoft_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Microsoft Translate API Key.
        /// </summary>
        public static string MicrosoftApiDescription {
            get {
                return ResourceManager.GetString("MicrosoftApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Private Endpoint Url.
        /// </summary>
        public static string MicrosoftPeDescription {
            get {
                return ResourceManager.GetString("MicrosoftPeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator with Private Endpoint.
        /// </summary>
        public static string MicrosoftWithPe {
            get {
                return ResourceManager.GetString("MicrosoftWithPe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error: bad credentials.
        /// </summary>
        public static string MsApiBadCredentialsMessage {
            get {
                return ResourceManager.GetString("MsApiBadCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category ID. Use a valid category ID or disable category ID in settings..
        /// </summary>
        public static string MsApiCategoryIdErrorMessage {
            get {
                return ResourceManager.GetString("MsApiCategoryIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get languages for translation.
        /// </summary>
        public static string MsApiFailedGetLanguagesMessage {
            get {
                return ResourceManager.GetString("MsApiFailedGetLanguagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to translate.
        /// </summary>
        public static string MsApiFailedToTranslateMessage {
            get {
                return ResourceManager.GetString("MsApiFailedToTranslateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Region:.
        /// </summary>
        public static string MSSubscriptionRegionLabel {
            get {
                return ResourceManager.GetString("MSSubscriptionRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon my_icon {
            get {
                object obj = ResourceManager.GetObject("my_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap my_image {
            get {
                object obj = ResourceManager.GetObject("my_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Google key.
        /// </summary>
        public static string PersistGoogle {
            get {
                return ResourceManager.GetString("PersistGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Microsoft key.
        /// </summary>
        public static string PersistMicrosoft {
            get {
                return ResourceManager.GetString("PersistMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Endpont Url not valid.
        /// </summary>
        public static string PeUrlError {
            get {
                return ResourceManager.GetString("PeUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Trados Plugin - Choose between Google Translate or Microsoft Translator.
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Trados Plugin.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Trados Plugin.
        /// </summary>
        public static string Plugin_NiceName {
            get {
                return ResourceManager.GetString("Plugin_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Trados Plugin - Choose between Google Translate or Microsoft Translator.
        /// </summary>
        public static string Plugin_Tooltip {
            get {
                return ResourceManager.GetString("Plugin_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginsView.
        /// </summary>
        public static string PluginsView {
            get {
                return ResourceManager.GetString("PluginsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostLookup.
        /// </summary>
        public static string PostLookupBrowse {
            get {
                return ResourceManager.GetString("PostLookupBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do post-lookup find/replace.
        /// </summary>
        public static string PostLookupDescription {
            get {
                return ResourceManager.GetString("PostLookupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-lookup filepath cannot be empty. Please add a valid path otherwise uncheck &quot;Do post-lookup checkbox&quot;..
        /// </summary>
        public static string PostLookupEmptyMessage {
            get {
                return ResourceManager.GetString("PostLookupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do post-lookup find/replace filename:.
        /// </summary>
        public static string PostLookupFileName {
            get {
                return ResourceManager.GetString("PostLookupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse or type the location of the post-lookup file.
        /// </summary>
        public static string PostLookupWaterMark {
            get {
                return ResourceManager.GetString("PostLookupWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-lookup file could not be found at the specified path..
        /// </summary>
        public static string PostLookupWrongPathMessage {
            get {
                return ResourceManager.GetString("PostLookupWrongPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreLookup.
        /// </summary>
        public static string PreLookBrowse {
            get {
                return ResourceManager.GetString("PreLookBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pre-lookup find/replace.
        /// </summary>
        public static string PreLookDescription {
            get {
                return ResourceManager.GetString("PreLookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pre-lookup find/replace name:.
        /// </summary>
        public static string PreLookFileName {
            get {
                return ResourceManager.GetString("PreLookFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-lookup filepath cannot be empty. Please add a valid path otherwise uncheck &quot;Do pre-lookup checkbox&quot;..
        /// </summary>
        public static string PreLookupEmptyMessage {
            get {
                return ResourceManager.GetString("PreLookupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse or type the location of the pre-lookup file.
        /// </summary>
        public static string PreLookupWaterMark {
            get {
                return ResourceManager.GetString("PreLookupWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-lookup file could not be found at the specified path..
        /// </summary>
        public static string PreLookupWrongPathMessage {
            get {
                return ResourceManager.GetString("PreLookupWrongPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project location value is required.
        /// </summary>
        public static string ProjectLocationValidation {
            get {
                return ResourceManager.GetString("ProjectLocationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for Google Translate....
        /// </summary>
        public static string PromptForCredentialsCaption_Google {
            get {
                return ResourceManager.GetString("PromptForCredentialsCaption_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for Microsoft Translator....
        /// </summary>
        public static string PromptForCredentialsCaption_Microsoft {
            get {
                return ResourceManager.GetString("PromptForCredentialsCaption_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send draft and translated segments.
        /// </summary>
        public static string ReSendDescription {
            get {
                return ResourceManager.GetString("ReSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send plain text only (not tags).
        /// </summary>
        public static string SendPlainDescription {
            get {
                return ResourceManager.GetString("SendPlainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Setting {
            get {
                object obj = ResourceManager.GetObject("Setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Provider Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsView.
        /// </summary>
        public static string SettingsView {
            get {
                return ResourceManager.GetString("SettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider options.
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [segment already translated...source not re-sent].
        /// </summary>
        public static string TranslationLookupDraftNotResentMessage {
            get {
                return ResourceManager.GetString("TranslationLookupDraftNotResentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidirectional glossaries.
        /// </summary>
        public static string UnidirectionalGlossary {
            get {
                return ResourceManager.GetString("UnidirectionalGlossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mtenhancedprovidergt:///.
        /// </summary>
        public static string UriGt {
            get {
                return ResourceManager.GetString("UriGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mtenhancedprovidermst:///.
        /// </summary>
        public static string UriMs {
            get {
                return ResourceManager.GetString("UriMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation provider URI not supported..
        /// </summary>
        public static string UriNotSupportedMessage {
            get {
                return ResourceManager.GetString("UriNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URI where the glossary is stored:.
        /// </summary>
        public static string V3Glossary {
            get {
                return ResourceManager.GetString("V3Glossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the local path to the json file associated with your API key:.
        /// </summary>
        public static string V3JsonPathDescription {
            get {
                return ResourceManager.GetString("V3JsonPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the project name for this file from your Google account:.
        /// </summary>
        public static string V3ProjectNameDescription {
            get {
                return ResourceManager.GetString("V3ProjectNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose which MT Provider you want to use:.
        /// </summary>
        public static string WindowDescription {
            get {
                return ResourceManager.GetString("WindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WindowsControl_Close {
            get {
                return ResourceManager.GetString("WindowsControl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json file could not be found at the specified path..
        /// </summary>
        public static string WrongJsonFilePath {
            get {
                return ResourceManager.GetString("WrongJsonFilePath", resourceCulture);
            }
        }
    }
}
