//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.AmazonTranslateTradosPlugin {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.AmazonTranslateTradosPlugin.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap amazon_aws_small {
            get {
                object obj = ResourceManager.GetObject("amazon_aws_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error: bad credentials.
        /// </summary>
        public static string AwsApiBadCredentialsMessage {
            get {
                return ResourceManager.GetString("AwsApiBadCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get languages for translation.
        /// </summary>
        public static string AwsApiFailedGetLanguagesMessage {
            get {
                return ResourceManager.GetString("AwsApiFailedGetLanguagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to translate.
        /// </summary>
        public static string AwsApiFailedToTranslateMessage {
            get {
                return ResourceManager.GetString("AwsApiFailedToTranslateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings error.
        /// </summary>
        public static string EditSettingsErrorCaption {
            get {
                return ResourceManager.GetString("EditSettingsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with edit settings:.
        /// </summary>
        public static string EditSettingsGenericErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation..
        /// </summary>
        public static string EditSettingsXmlErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsXmlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon my_icon {
            get {
                object obj = ResourceManager.GetObject("my_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmazonTranslate Trados Plugin.
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmazonTranslate Trados Plugin.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Translate Trados Plugin.
        /// </summary>
        public static string Plugin_NiceName {
            get {
                return ResourceManager.GetString("Plugin_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Translate Trados Plugin.
        /// </summary>
        public static string Plugin_Tooltip {
            get {
                return ResourceManager.GetString("Plugin_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for AmazonTranslate....
        /// </summary>
        public static string PromptForCredentialsCaption {
            get {
                return ResourceManager.GetString("PromptForCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [segment already translated...source not re-sent].
        /// </summary>
        public static string TranslationLookupDraftNotResentMessage {
            get {
                return ResourceManager.GetString("TranslationLookupDraftNotResentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation provider URI not supported..
        /// </summary>
        public static string UriNotSupportedMessage {
            get {
                return ResourceManager.GetString("UriNotSupportedMessage", resourceCulture);
            }
        }
    }
}
