//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.TranslationMemoryManagementUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.TranslationMemoryManagementUtility.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to modify TM &apos;{0}&apos;..
        /// </summary>
        internal static string accessFileSkipped {
            get {
                return ResourceManager.GetString("accessFileSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation memory &apos;{0}&apos; is password-protected. Please enter administrator level password to continue:.
        /// </summary>
        internal static string accessSubTitle {
            get {
                return ResourceManager.GetString("accessSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assembly check..
        /// </summary>
        internal static string AssemblyProblemTitle {
            get {
                return ResourceManager.GetString("AssemblyProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password to continue..
        /// </summary>
        internal static string errEmptyPsw {
            get {
                return ResourceManager.GetString("errEmptyPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nCannot process file &apos;{0}&apos;.\r\nThis type of file is not supported.\r\n.
        /// </summary>
        internal static string errFileNotSupported {
            get {
                return ResourceManager.GetString("errFileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string errInvalidPsw {
            get {
                return ResourceManager.GetString("errInvalidPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove duplicates in file &apos;{0}&apos;.\r\nDetails: {1}\r\n.
        /// </summary>
        internal static string errRemDupTaskFailed {
            get {
                return ResourceManager.GetString("errRemDupTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks were detected in directory &apos;{0}&apos;. Translation Memory Management tool cannot be loaded..
        /// </summary>
        internal static string errTasksNotFound {
            get {
                return ResourceManager.GetString("errTasksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of files is empty..
        /// </summary>
        internal static string filesEmptyList {
            get {
                return ResourceManager.GetString("filesEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files selected..
        /// </summary>
        internal static string filesEmptySelectedList {
            get {
                return ResourceManager.GetString("filesEmptySelectedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select translation memory files to process..
        /// </summary>
        internal static string filesFileDialogTitle {
            get {
                return ResourceManager.GetString("filesFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to Files tab and add files to process..
        /// </summary>
        internal static string findFilesNotAdded {
            get {
                return ResourceManager.GetString("findFilesNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task finished successfully. \r\n.
        /// </summary>
        internal static string logTaskFinished {
            get {
                return ResourceManager.GetString("logTaskFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started performing {0} task in file(s)...\r\n.
        /// </summary>
        internal static string logTaskStarted {
            get {
                return ResourceManager.GetString("logTaskStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites check..
        /// </summary>
        internal static string PrerequisitesProblemTitle {
            get {
                return ResourceManager.GetString("PrerequisitesProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} of {1}:.
        /// </summary>
        internal static string progressFile {
            get {
                return ResourceManager.GetString("progressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing files..
        /// </summary>
        internal static string progressFileFinished {
            get {
                return ResourceManager.GetString("progressFileFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Memory Management.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TranslationMemory {
            get {
                object obj = ResourceManager.GetObject("TranslationMemory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load task assembly &apos;{0}&apos;.\r\nDetails: {1}.
        /// </summary>
        internal static string wrnTaskAssVersion {
            get {
                return ResourceManager.GetString("wrnTaskAssVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load task assembly &apos;{0}&apos;. It does not contain requited types..
        /// </summary>
        internal static string wrnTaskTypesMissing {
            get {
                return ResourceManager.GetString("wrnTaskTypesMissing", resourceCulture);
            }
        }
    }
}
