trigger:
  branches:
    include:
     - master
  paths:
    include:
     - ApplyTM Template/*

pr:
  branches:
    include:
     - master
  paths:
    include:
     - ApplyTM Template/*

variables: 
- group: 'ApplyTMTemplateSonarVersion'
- template: build/jobs/branch-variables.yml
- name: buildPlatform 
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: pathToPublish
  value: 'ApplyTM Template\Sdl.Community.ApplyTMTemplate\bin\Release\net48\Sdl.Community.ApplyTMTemplate.sdlplugin'
- name: solution
  value: '**/Sdl.Community.ApplyTMTemplate.sln'
- name : SonarID
  value : ApplyTM_Template
- name : SonarName
  value : 'ApplyTM Template'
- name : ProjectVersion
  value : $[counter(variables['Version.Patch'], 1)]

pool:
  vmImage: '$(DefaultBuildVm)'

steps:
  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'AppStorePlugins-ServiceConnection'
      organization: 'sdl'
      scannerMode: 'dotnet'
      projectKey: $(SonarId)
      projectName: $(SonarName)
      projectVersion: $(ProjectVersion)

  - template: build/jobs/build-sdlplugin.yml
  - task: SonarCloudAnalyze@3
    displayName: 'Run Code Analysis'

  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Quality Gate Result'

  - template: build/jobs/publish-build-artifact-task.yml
