# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Code samples/MultiTermStandAloneTestApp/MultiTermStandAloneTestApp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: 'Code samples/MultiTermStandAloneTestApp/MultiTermStandAloneTestApp.sln'
    vsVersion: '15.0'
    clean: false
    maximumCpuCount: false
    msbuildArchitecture: x64
    logProjectEvents: true
    createLogFile: false
    logFileVerbosity: 'normal'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
