//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Utilities.SplitSDLXLIFF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Utilities.SplitSDLXLIFF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files merge failed!.
        /// </summary>
        internal static string errMerge {
            get {
                return ResourceManager.GetString("errMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified split files folder does not exist..
        /// </summary>
        internal static string errMergeFolderNotExist {
            get {
                return ResourceManager.GetString("errMergeFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Splitinfo file does not exist..
        /// </summary>
        internal static string errMergeInfoFileNotExist {
            get {
                return ResourceManager.GetString("errMergeInfoFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.\r\nNo files were merged..
        /// </summary>
        internal static string errMergeNoFiles {
            get {
                return ResourceManager.GetString("errMergeNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify split files folder..
        /// </summary>
        internal static string errMergeNoFolder {
            get {
                return ResourceManager.GetString("errMergeNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify split info file..
        /// </summary>
        internal static string errMergeNoInfoFile {
            get {
                return ResourceManager.GetString("errMergeNoInfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify original file..
        /// </summary>
        internal static string errMergeNoOrigFile {
            get {
                return ResourceManager.GetString("errMergeNoOrigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified original file does not exist..
        /// </summary>
        internal static string errMergeOrigFileNotExist {
            get {
                return ResourceManager.GetString("errMergeOrigFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.\r\nERROR: {0}.
        /// </summary>
        internal static string errMergeUnexp {
            get {
                return ResourceManager.GetString("errMergeUnexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files split failed!.
        /// </summary>
        internal static string errSplit {
            get {
                return ResourceManager.GetString("errSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified target folder does not exist..
        /// </summary>
        internal static string errSplitFolderNotExist {
            get {
                return ResourceManager.GetString("errSplitFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify file to split..
        /// </summary>
        internal static string errSplitNoFile {
            get {
                return ResourceManager.GetString("errSplitNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.\r\nNo files were created.\r\n.
        /// </summary>
        internal static string errSplitNoFiles {
            get {
                return ResourceManager.GetString("errSplitNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify target folder..
        /// </summary>
        internal static string errSplitNoFolder {
            get {
                return ResourceManager.GetString("errSplitNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate valid segment numbers to split the file by..
        /// </summary>
        internal static string errSplitSegNumbers {
            get {
                return ResourceManager.GetString("errSplitSegNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.\r\nERROR: {0}.
        /// </summary>
        internal static string errSplitUnexp {
            get {
                return ResourceManager.GetString("errSplitUnexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SDLXLIFF file to split..
        /// </summary>
        internal static string FileDialogTitle {
            get {
                return ResourceManager.GetString("FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target languages selected..
        /// </summary>
        internal static string filesNoTargetLanguage {
            get {
                return ResourceManager.GetString("filesNoTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Split Info file..
        /// </summary>
        internal static string InfoFileDialogTitle {
            get {
                return ResourceManager.GetString("InfoFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL Trados Studio  is not licensed on this computer. Activate it first before using this add-on..
        /// </summary>
        internal static string LicenseErrorMessage {
            get {
                return ResourceManager.GetString("LicenseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Settings..
        /// </summary>
        internal static string MergeSettingsTitle {
            get {
                return ResourceManager.GetString("MergeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Task..
        /// </summary>
        internal static string MergeTitle {
            get {
                return ResourceManager.GetString("MergeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished merging files..
        /// </summary>
        internal static string msbMergeFinished {
            get {
                return ResourceManager.GetString("msbMergeFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished splitting files..
        /// </summary>
        internal static string msbSplitFinished {
            get {
                return ResourceManager.GetString("msbSplitFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with errors..
        /// </summary>
        internal static string msbSplitFinishedWithErr {
            get {
                return ResourceManager.GetString("msbSplitFinishedWithErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of files is empty..
        /// </summary>
        internal static string msgEmptyList {
            get {
                return ResourceManager.GetString("msgEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to the original SDLXLIFF file, the folder with split files as well as the path to the split info file..
        /// </summary>
        internal static string msgMergeFOptsSubtitle {
            get {
                return ResourceManager.GetString("msgMergeFOptsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for Merge Task.
        /// </summary>
        internal static string msgMergeFOptsTitle {
            get {
                return ResourceManager.GetString("msgMergeFOptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task finished successfully.\r\nNumber of files merged: {0}.\r\n.
        /// </summary>
        internal static string msgMergeScc {
            get {
                return ResourceManager.GetString("msgMergeScc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files merge started...\r\n.
        /// </summary>
        internal static string msgMergeStart {
            get {
                return ResourceManager.GetString("msgMergeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the files are being merged..
        /// </summary>
        internal static string msgMergeSubtitle {
            get {
                return ResourceManager.GetString("msgMergeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging Files....
        /// </summary>
        internal static string msgMergeTitle {
            get {
                return ResourceManager.GetString("msgMergeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nMerging files to &apos;{0}&apos;...\r\n.
        /// </summary>
        internal static string msgMerging {
            get {
                return ResourceManager.GetString("msgMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.\r\nCannot process the file. The file is corrupt or contains more than one merged in Trados Studio SDLXLIFF files.\r\n.
        /// </summary>
        internal static string msgSplitCorruptFile {
            get {
                return ResourceManager.GetString("msgSplitCorruptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished splitting files. Number of files processed: {0}..
        /// </summary>
        internal static string msgSplitFinished {
            get {
                return ResourceManager.GetString("msgSplitFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the files to split and indicate where the split files should be copied..
        /// </summary>
        internal static string msgSplitFOptsSubtitle {
            get {
                return ResourceManager.GetString("msgSplitFOptsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Management Settings for Split Task.
        /// </summary>
        internal static string msgSplitFOptsTitle {
            get {
                return ResourceManager.GetString("msgSplitFOptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the rules governing how the files should be split..
        /// </summary>
        internal static string msgSplitOptsSubtitle {
            get {
                return ResourceManager.GetString("msgSplitOptsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for Split Task.
        /// </summary>
        internal static string msgSplitOptsTitle {
            get {
                return ResourceManager.GetString("msgSplitOptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task finished successfully.\r\nNumber of split files created: {0}.\r\n.
        /// </summary>
        internal static string msgSplitScc {
            get {
                return ResourceManager.GetString("msgSplitScc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File split started...\r\n.
        /// </summary>
        internal static string msgSplitStart {
            get {
                return ResourceManager.GetString("msgSplitStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the files are being split..
        /// </summary>
        internal static string msgSplitSubtitle {
            get {
                return ResourceManager.GetString("msgSplitSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nSplitting &apos;{0}&apos;...\r\n.
        /// </summary>
        internal static string msgSplitting {
            get {
                return ResourceManager.GetString("msgSplitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting files ({0} of {1}):.
        /// </summary>
        internal static string msgSplittingFiles {
            get {
                return ResourceManager.GetString("msgSplittingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting Files....
        /// </summary>
        internal static string msgSplitTitle {
            get {
                return ResourceManager.GetString("msgSplitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: The number of files created is different from the number of split parts you requested.\r\nThe Application does split of text within a segment, so in some cases, when the input file is too small, or the number of split parts too high, the number of files created may be less than indicated.\r\n.
        /// </summary>
        internal static string msgSplitWarning {
            get {
                return ResourceManager.GetString("msgSplitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDLXLIFF Split/Merge allows you to split large SDLXLIFF files and re-merge them back into one file after translation or review. Indicate the task you would like to perform..
        /// </summary>
        internal static string msgWelcomeSubtitle {
            get {
                return ResourceManager.GetString("msgWelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SDLXLIFF Split/Merge.
        /// </summary>
        internal static string msgWelcomeTitle {
            get {
                return ResourceManager.GetString("msgWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select original SDLXLIFF file..
        /// </summary>
        internal static string OrigFileDialogTitle {
            get {
                return ResourceManager.GetString("OrigFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string PrerequisitesProblemTitle {
            get {
                return ResourceManager.GetString("PrerequisitesProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SDL Trados Studio project file.
        /// </summary>
        internal static string ProjectFileDialogTitle {
            get {
                return ResourceManager.GetString("ProjectFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a path for split files..
        /// </summary>
        internal static string SplitFilesDialogDesc {
            get {
                return ResourceManager.GetString("SplitFilesDialogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Settings..
        /// </summary>
        internal static string SplitSettingsTitle {
            get {
                return ResourceManager.GetString("SplitSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Task..
        /// </summary>
        internal static string SplitTitle {
            get {
                return ResourceManager.GetString("SplitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a target path..
        /// </summary>
        internal static string TargetPathDialogDesc {
            get {
                return ResourceManager.GetString("TargetPathDialogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDLXLIFF Split and Merge.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
