//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTEnhancedMicrosoftProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTEnhancedMicrosoftProvider.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTEnhanced.
        /// </summary>
        public static string AppLogFolder {
            get {
                return ResourceManager.GetString("AppLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings error.
        /// </summary>
        public static string EditSettingsErrorCaption {
            get {
                return ResourceManager.GetString("EditSettingsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with edit settings:.
        /// </summary>
        public static string EditSettingsGenericErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation..
        /// </summary>
        public static string EditSettingsXmlErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsXmlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTEnhancedLogs.txt.
        /// </summary>
        public static string LogsFileName {
            get {
                return ResourceManager.GetString("LogsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWS AppStore.
        /// </summary>
        public static string LogsFolderPath {
            get {
                return ResourceManager.GetString("LogsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translation.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_Description {
            get {
                return ResourceManager.GetString("Microsoft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_Name {
            get {
                return ResourceManager.GetString("Microsoft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_NiceName {
            get {
                return ResourceManager.GetString("Microsoft_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced using Microsoft Translator.
        /// </summary>
        public static string Microsoft_Tooltip {
            get {
                return ResourceManager.GetString("Microsoft_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Microsoft Translate API Key.
        /// </summary>
        public static string MicrosoftApiDescription {
            get {
                return ResourceManager.GetString("MicrosoftApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error: bad credentials.
        /// </summary>
        public static string MsApiBadCredentialsMessage {
            get {
                return ResourceManager.GetString("MsApiBadCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category ID. Use a valid category ID or disable category ID in settings..
        /// </summary>
        public static string MsApiCategoryIdErrorMessage {
            get {
                return ResourceManager.GetString("MsApiCategoryIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get languages for translation.
        /// </summary>
        public static string MsApiFailedGetLanguagesMessage {
            get {
                return ResourceManager.GetString("MsApiFailedGetLanguagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to translate.
        /// </summary>
        public static string MsApiFailedToTranslateMessage {
            get {
                return ResourceManager.GetString("MsApiFailedToTranslateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Region:.
        /// </summary>
        public static string MSSubscriptionRegionLabel {
            get {
                return ResourceManager.GetString("MSSubscriptionRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Trados Plugin - Choose between Google Translate or Microsoft Translator.
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTEnhancedMicrosoftProvider.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Trados Plugin.
        /// </summary>
        public static string Plugin_NiceName {
            get {
                return ResourceManager.GetString("Plugin_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostLookup.
        /// </summary>
        public static string PostLookupBrowse {
            get {
                return ResourceManager.GetString("PostLookupBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreLookup.
        /// </summary>
        public static string PreLookBrowse {
            get {
                return ResourceManager.GetString("PreLookBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [segment already translated...source not re-sent].
        /// </summary>
        public static string TranslationLookupDraftNotResentMessage {
            get {
                return ResourceManager.GetString("TranslationLookupDraftNotResentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mtenhancedprovidermst:///.
        /// </summary>
        public static string UriMs {
            get {
                return ResourceManager.GetString("UriMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation provider URI not supported..
        /// </summary>
        public static string UriNotSupportedMessage {
            get {
                return ResourceManager.GetString("UriNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WindowsControl_Close {
            get {
                return ResourceManager.GetString("WindowsControl_Close", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		public static System.Drawing.Icon ForumIcon
		{
			get
			{
				object obj = ResourceManager.GetObject("ForumIcon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		public static System.Drawing.Icon Download
		{
			get
			{
				object obj = ResourceManager.GetObject("Download", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		public static System.Drawing.Icon Settings
		{
			get
			{
				object obj = ResourceManager.GetObject("Settings", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		public static System.Drawing.Icon Question
		{
			get
			{
				object obj = ResourceManager.GetObject("Question", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
	}
}
