//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.ProjectTerms.Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.ProjectTerms.Plugin.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon applogo {
            get {
                object obj = ResourceManager.GetObject("applogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackListTerms.txt.
        /// </summary>
        public static string BlacklistFileName {
            get {
                return ResourceManager.GetString("BlacklistFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Terms From Selected Files.
        /// </summary>
        public static string Button_ExtractTermsFiles {
            get {
                return ResourceManager.GetString("Button_ExtractTermsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Terms From Project.
        /// </summary>
        public static string Button_ExtractTermsProject {
            get {
                return ResourceManager.GetString("Button_ExtractTermsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _project.
        /// </summary>
        public static string Constant_ProjectType {
            get {
                return ResourceManager.GetString("Constant_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleFile.
        /// </summary>
        public static string Constant_ProjectTypeContent {
            get {
                return ResourceManager.GetString("Constant_ProjectTypeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add languages to the termbase definition file!.
        /// </summary>
        public static string Error_AddLanguages {
            get {
                return ResourceManager.GetString("Error_AddLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the XML file to the project!.
        /// </summary>
        public static string Error_AddXMlToProject {
            get {
                return ResourceManager.GetString("Error_AddXMlToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the termbase repository!.
        /// </summary>
        public static string Error_ConnectToTermbaseLocalRepository {
            get {
                return ResourceManager.GetString("Error_ConnectToTermbaseLocalRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the folder!.
        /// </summary>
        public static string Error_CreateDirectory {
            get {
                return ResourceManager.GetString("Error_CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the XML entry!.
        /// </summary>
        public static string Error_CreateEntry {
            get {
                return ResourceManager.GetString("Error_CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate the termbase!.
        /// </summary>
        public static string Error_CreateTermbase {
            get {
                return ResourceManager.GetString("Error_CreateTermbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract the SDLXLIFF content!.
        /// </summary>
        public static string Error_ExtractContent {
            get {
                return ResourceManager.GetString("Error_ExtractContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the project languages!.
        /// </summary>
        public static string Error_GetProjectLanguages {
            get {
                return ResourceManager.GetString("Error_GetProjectLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract the embedded resource file!.
        /// </summary>
        public static string Error_GetResourceTextFile {
            get {
                return ResourceManager.GetString("Error_GetResourceTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the termbase in Studio!.
        /// </summary>
        public static string Error_IncludeTermbaseInStudio {
            get {
                return ResourceManager.GetString("Error_IncludeTermbaseInStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the termbase!.
        /// </summary>
        public static string Error_PopulateTermbase {
            get {
                return ResourceManager.GetString("Error_PopulateTermbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please extract the terms first!.
        /// </summary>
        public static string Error_ReadXmlFile {
            get {
                return ResourceManager.GetString("Error_ReadXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression, please review the rules!.
        /// </summary>
        public static string Error_Regex {
            get {
                return ResourceManager.GetString("Error_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the folder!.
        /// </summary>
        public static string Error_RemoveDirectory {
            get {
                return ResourceManager.GetString("Error_RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the XML file!.
        /// </summary>
        public static string Error_Save {
            get {
                return ResourceManager.GetString("Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the termbase definition!.
        /// </summary>
        public static string Error_SaveTermbaseDefinitionToTempLocation {
            get {
                return ResourceManager.GetString("Error_SaveTermbaseDefinitionToTempLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the termbase settings!.
        /// </summary>
        public static string Error_Settings {
            get {
                return ResourceManager.GetString("Error_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Terms cannot be used on a single file project. Please create a standard Studio project and try again..
        /// </summary>
        public static string Error_SingleFileProject {
            get {
                return ResourceManager.GetString("Error_SingleFileProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found!.
        /// </summary>
        public static string Info_NotMatch {
            get {
                return ResourceManager.GetString("Info_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your termbase was successfully added to the project!.
        /// </summary>
        public static string Info_SuccessfullyAdded {
            get {
                return ResourceManager.GetString("Info_SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   1. Go to Project Settings -&gt; All Language Pairs -&gt; Termbases and remove the 	termbase from your Project and then close Studio
        ///  2. Go to your Projects folder in Windows Explorer and delete the Tb folder
        ///  3. Go to c:\Users\[username]\AppData\Local\Temp\ and delete the Tb folder
        ///
        ///Restart Studio and now you should be able to generate the new termbase..
        /// </summary>
        public static string Info_TermbaseExists {
            get {
                return ResourceManager.GetString("Info_TermbaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terms were extracted successfully..
        /// </summary>
        public static string Message_ExtractedTerms {
            get {
                return ResourceManager.GetString("Message_ExtractedTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term exists in the list!.
        /// </summary>
        public static string MessageContent_buttonAdd {
            get {
                return ResourceManager.GetString("MessageContent_buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is empty!.
        /// </summary>
        public static string MessageContent_buttonDelete_Empty {
            get {
                return ResourceManager.GetString("MessageContent_buttonDelete_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one term!.
        /// </summary>
        public static string MessageContent_buttonDelete_Select {
            get {
                return ResourceManager.GetString("MessageContent_buttonDelete_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the blacklist! Please save the list once!.
        /// </summary>
        public static string MessageContent_buttonLoad {
            get {
                return ResourceManager.GetString("MessageContent_buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only generate the termbase from the extracted project terms XML file..
        /// </summary>
        public static string MessageContent_GenerateTermbaseAction {
            get {
                return ResourceManager.GetString("MessageContent_GenerateTermbaseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be run for multiples files!.
        /// </summary>
        public static string MessageContent_multipleFilesTermbase {
            get {
                return ResourceManager.GetString("MessageContent_multipleFilesTermbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open the settings window!.
        /// </summary>
        public static string MessageContent_SkipSettings {
            get {
                return ResourceManager.GetString("MessageContent_SkipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termbase information.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageType_Error {
            get {
                return ResourceManager.GetString("MessageType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageType_Info {
            get {
                return ResourceManager.GetString("MessageType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdl.Community.ProjectTerms.Plugin.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectTerms-sourcecloud.
        /// </summary>
        public static string WordCloudFileName {
            get {
                return ResourceManager.GetString("WordCloudFileName", resourceCulture);
            }
        }
    }
}
