//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleCloudTranslationProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleCloudTranslationProvider.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key has been set.  Please open the plugin settings form and enter a valid API key.
        /// </summary>
        public static string ApiConnectionGoogleNoKeyErrorMessage {
            get {
                return ResourceManager.GetString("ApiConnectionGoogleNoKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backImg {
            get {
                object obj = ResourceManager.GetObject("backImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings error.
        /// </summary>
        public static string EditSettingsErrorCaption {
            get {
                return ResourceManager.GetString("EditSettingsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with edit settings:.
        /// </summary>
        public static string EditSettingsGenericErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation..
        /// </summary>
        public static string EditSettingsXmlErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsXmlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while downloading the file..
        /// </summary>
        public static string FileValidation_DownloadFailed {
            get {
                return ResourceManager.GetString("FileValidation_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url can not be empty..
        /// </summary>
        public static string FileValidation_EmptyUri {
            get {
                return ResourceManager.GetString("FileValidation_EmptyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found at the selected location. The file could have been renamed, deleted or moved from when it was loaded..
        /// </summary>
        public static string FileValidation_FileDoesNotExists {
            get {
                return ResourceManager.GetString("FileValidation_FileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected json file has {0} fields than it is supposed to have. Please download the file again and use an unedited file..
        /// </summary>
        public static string FileValidation_JsonFileFields {
            get {
                return ResourceManager.GetString("FileValidation_JsonFileFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a valid JSON file that could be downloaded..
        /// </summary>
        public static string FileValidation_MissingJsonFile {
            get {
                return ResourceManager.GetString("FileValidation_MissingJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file must be of .json type..
        /// </summary>
        public static string FileValidation_NotJsonType {
            get {
                return ResourceManager.GetString("FileValidation_NotJsonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected path does not exists.
        ///Path: {0}.
        /// </summary>
        public static string FileValidation_PathDoesNotExists {
            get {
                return ResourceManager.GetString("FileValidation_PathDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while trying to read the file. The file might be corrupted..
        /// </summary>
        public static string FileValidation_ReadingJsonFailed {
            get {
                return ResourceManager.GetString("FileValidation_ReadingJsonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path must be set..
        /// </summary>
        public static string FileValidation_UnsetFilePath {
            get {
                return ResourceManager.GetString("FileValidation_UnsetFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ForumIcon {
            get {
                object obj = ResourceManager.GetObject("ForumIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translator - What is this.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate G_Description.
        /// </summary>
        public static string Google_Description {
            get {
                return ResourceManager.GetString("Google_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate G_Name.
        /// </summary>
        public static string Google_Name {
            get {
                return ResourceManager.GetString("Google_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate G_NiceName.
        /// </summary>
        public static string Google_NiceName {
            get {
                return ResourceManager.GetString("Google_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate G_ToolTip.
        /// </summary>
        public static string Google_Tooltip {
            get {
                return ResourceManager.GetString("Google_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate - V3 Advanced Translation.
        /// </summary>
        public static string GoogleAdvanced {
            get {
                return ResourceManager.GetString("GoogleAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the version of the Google TP and sign in using your credentials.
        /// </summary>
        public static string GoogleApiDescription {
            get {
                return ResourceManager.GetString("GoogleApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2 - Basic Translation.
        /// </summary>
        public static string GoogleApiVersionV2Description {
            get {
                return ResourceManager.GetString("GoogleApiVersionV2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3 - Advanced Translation.
        /// </summary>
        public static string GoogleApiVersionV3Description {
            get {
                return ResourceManager.GetString("GoogleApiVersionV3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate - V2 Basic Translation.
        /// </summary>
        public static string GoogleBasic {
            get {
                return ResourceManager.GetString("GoogleBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter AutoML Translation model:.
        /// </summary>
        public static string GoogleEngineModelDescription {
            get {
                return ResourceManager.GetString("GoogleEngineModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add project location:.
        /// </summary>
        public static string GoogleProjectLocation {
            get {
                return ResourceManager.GetString("GoogleProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Response.
        /// </summary>
        public static string GoogleResponseDescription {
            get {
                return ResourceManager.GetString("GoogleResponseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google API Version.
        /// </summary>
        public static string GroupboxHeaders_GoogleApi {
            get {
                return ResourceManager.GetString("GroupboxHeaders_GoogleApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project info.
        /// </summary>
        public static string GroupboxHeaders_ProjectInfo {
            get {
                return ResourceManager.GetString("GroupboxHeaders_ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GroupboxHeaders_Settings {
            get {
                return ResourceManager.GetString("GroupboxHeaders_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem checking language pair support..
        /// </summary>
        public static string LangPairAuthErrorMsg1 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that you have entered the correct API key..
        /// </summary>
        public static string LangPairAuthErrorMsg2 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, close/reopen the current dialog and try again.
        /// </summary>
        public static string LangPairAuthErrorMsg3 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close app.
        /// </summary>
        public static string MainView_CloseButton {
            get {
                return ResourceManager.GetString("MainView_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MainView_ConfirmButton {
            get {
                return ResourceManager.GetString("MainView_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainView_HelpButton {
            get {
                return ResourceManager.GetString("MainView_HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string MultiButton_Provider {
            get {
                return ResourceManager.GetString("MultiButton_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MultiButton_Settings {
            get {
                return ResourceManager.GetString("MultiButton_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon my_icon {
            get {
                object obj = ResourceManager.GetObject("my_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap my_image {
            get {
                object obj = ResourceManager.GetObject("my_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax for the NameOf is:
        ///&quot;{[location_of_NameOf]:NameOf Member=[PropertyName], Type={x:Type[classLocation:ClassName]}}&quot;
        ///Your values should go inside each [], eg: [PropertyName] =&gt; ProjectId.
        /// </summary>
        public static string NameOf_CommandParameter_Syntax {
            get {
                return ResourceManager.GetString("NameOf_CommandParameter_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the property [&apos;{0}&apos;] in [&apos;{1}&apos;], please check the spelling for both the property and the class or if any of the two had its name changed in both C# class and XAML..
        /// </summary>
        public static string NameOf_CommandParameterI_MissingComponent {
            get {
                return ResourceManager.GetString("NameOf_CommandParameterI_MissingComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translator Provider Plugin - Choose between V2 or V3 - Description.
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translator Provider - Plugin_Name.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translator Provider - Plugin_NiceName.
        /// </summary>
        public static string Plugin_NiceName {
            get {
                return ResourceManager.GetString("Plugin_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translator Provider Plugin - Choose between V2 or V3 - ToolTip.
        /// </summary>
        public static string Plugin_Tooltip {
            get {
                return ResourceManager.GetString("Plugin_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-lookup filepath cannot be empty. Please add a valid path otherwise uncheck &quot;Do post-lookup checkbox&quot;..
        /// </summary>
        public static string PostLookupEmptyMessage {
            get {
                return ResourceManager.GetString("PostLookupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do post-lookup find/replace filename:.
        /// </summary>
        public static string PostLookupFileName {
            get {
                return ResourceManager.GetString("PostLookupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-lookup file could not be found at the specified path..
        /// </summary>
        public static string PostLookupWrongPathMessage {
            get {
                return ResourceManager.GetString("PostLookupWrongPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-lookup filepath cannot be empty. Please add a valid path otherwise uncheck &quot;Do pre-lookup checkbox&quot;..
        /// </summary>
        public static string PreLookupEmptyMessage {
            get {
                return ResourceManager.GetString("PreLookupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-lookup file could not be found at the specified path..
        /// </summary>
        public static string PreLookupWrongPathMessage {
            get {
                return ResourceManager.GetString("PreLookupWrongPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Model.
        /// </summary>
        public static string ProjectInfo_CustomModel {
            get {
                return ResourceManager.GetString("ProjectInfo_CustomModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not use a custom model..
        /// </summary>
        public static string ProjectInfo_CustomModelNotUsed {
            get {
                return ResourceManager.GetString("ProjectInfo_CustomModelNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not use a glossary..
        /// </summary>
        public static string ProjectInfo_GlossaryNotUsed {
            get {
                return ResourceManager.GetString("ProjectInfo_GlossaryNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine the location of the project..
        /// </summary>
        public static string ProjectInfo_LocationMissing {
            get {
                return ResourceManager.GetString("ProjectInfo_LocationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine the json file path. The file was moved, renamed or deleted..
        /// </summary>
        public static string ProjectInfo_PathCorrupted {
            get {
                return ResourceManager.GetString("ProjectInfo_PathCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine the project id. The field is probably missing on the json file or the json file is corrupted..
        /// </summary>
        public static string ProjectInfo_ProjectIdMissing {
            get {
                return ResourceManager.GetString("ProjectInfo_ProjectIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for Google Translate....
        /// </summary>
        public static string PromptForCredentialsCaption_Google {
            get {
                return ResourceManager.GetString("PromptForCredentialsCaption_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Cloud API Key.
        /// </summary>
        public static string ProviderView_V2_ApiKey_Description {
            get {
                return ResourceManager.GetString("ProviderView_V2_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key Tooltip placeholder.
        /// </summary>
        public static string ProviderView_V2_ApiKey_Tooltip {
            get {
                return ResourceManager.GetString("ProviderView_V2_ApiKey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember key.
        /// </summary>
        public static string ProviderView_V2_RememberKey {
            get {
                return ResourceManager.GetString("ProviderView_V2_RememberKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom model (AutoML).
        /// </summary>
        public static string ProviderView_V3_CustomModel_Description {
            get {
                return ResourceManager.GetString("ProviderView_V3_CustomModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to your custom models.
        /// </summary>
        public static string ProviderView_V3_CustomModel_Navigate {
            get {
                return ResourceManager.GetString("ProviderView_V3_CustomModel_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Model (AutoML) Tooltip placeholder.
        /// </summary>
        public static string ProviderView_V3_CustomModel_Tooltip {
            get {
                return ResourceManager.GetString("ProviderView_V3_CustomModel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine name here.
        /// </summary>
        public static string ProviderView_V3_CustomModel_Watermark {
            get {
                return ResourceManager.GetString("ProviderView_V3_CustomModel_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or click here browse for it on your machine.
        /// </summary>
        public static string ProviderView_V3_File_Browse {
            get {
                return ResourceManager.GetString("ProviderView_V3_File_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ProviderView_V3_File_DownloadButton {
            get {
                return ResourceManager.GetString("ProviderView_V3_File_DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your JSON file.
        /// </summary>
        public static string ProviderView_V3_File_DragAndDrop {
            get {
                return ResourceManager.GetString("ProviderView_V3_File_DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary.
        /// </summary>
        public static string ProviderView_V3_Glossary_Description {
            get {
                return ResourceManager.GetString("ProviderView_V3_Glossary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to your glossaries.
        /// </summary>
        public static string ProviderView_V3_Glossary_Navigate {
            get {
                return ResourceManager.GetString("ProviderView_V3_Glossary_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary Tooltip placeholder.
        /// </summary>
        public static string ProviderView_V3_Glossary_Tooltip {
            get {
                return ResourceManager.GetString("ProviderView_V3_Glossary_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidirectional glossaries.
        /// </summary>
        public static string ProviderView_V3_Glossary_UseUnidirectional {
            get {
                return ResourceManager.GetString("ProviderView_V3_Glossary_UseUnidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary name here.
        /// </summary>
        public static string ProviderView_V3_Glossary_Watermark {
            get {
                return ResourceManager.GetString("ProviderView_V3_Glossary_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path.
        /// </summary>
        public static string ProviderView_V3_LocalPath_Description {
            get {
                return ResourceManager.GetString("ProviderView_V3_LocalPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can not be edited manualy, you need to use the -Drag and Drop- or -Browse- feature.
        /// </summary>
        public static string ProviderView_V3_LocalPath_Tooltip {
            get {
                return ResourceManager.GetString("ProviderView_V3_LocalPath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ProviderView_V3_Location_Description {
            get {
                return ResourceManager.GetString("ProviderView_V3_Location_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location Tooltip placeholder.
        /// </summary>
        public static string ProviderView_V3_Location_Tooltip {
            get {
                return ResourceManager.GetString("ProviderView_V3_Location_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project location here.
        /// </summary>
        public static string ProviderView_V3_Location_Watermark {
            get {
                return ResourceManager.GetString("ProviderView_V3_Location_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to your project.
        /// </summary>
        public static string ProviderView_V3_Project_Navigate {
            get {
                return ResourceManager.GetString("ProviderView_V3_Project_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID.
        /// </summary>
        public static string ProviderView_V3_ProjectID_Description {
            get {
                return ResourceManager.GetString("ProviderView_V3_ProjectID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID Tooltip placeholder.
        /// </summary>
        public static string ProviderView_V3_ProjectID_Tooltip {
            get {
                return ResourceManager.GetString("ProviderView_V3_ProjectID_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file is corrupted, the ProjectID is either missing or incorrect..
        /// </summary>
        public static string ProviderView_V3_ProjectID_Warning {
            get {
                return ResourceManager.GetString("ProviderView_V3_ProjectID_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type/paste your url here.
        /// </summary>
        public static string ProviderView_V3_Url_Watermark {
            get {
                return ResourceManager.GetString("ProviderView_V3_Url_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use URL.
        /// </summary>
        public static string ProviderView_V3_UseUrl {
            get {
                return ResourceManager.GetString("ProviderView_V3_UseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string ProviderViewModel_PathNotSpecified {
            get {
                return ResourceManager.GetString("ProviderViewModel_PathNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; No custom models available.
        /// </summary>
        public static string RetrievedResources_CustomModels_Unavailable {
            get {
                return ResourceManager.GetString("RetrievedResources_CustomModels_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; No custom model selected.
        /// </summary>
        public static string RetrievedResources_CustomModels_Unselected {
            get {
                return ResourceManager.GetString("RetrievedResources_CustomModels_Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; No glossaries available.
        /// </summary>
        public static string RetrievedResources_Glossaries_Unavailable {
            get {
                return ResourceManager.GetString("RetrievedResources_Glossaries_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; No glossary selected.
        /// </summary>
        public static string RetrievedResources_Glossaries_Unselected {
            get {
                return ResourceManager.GetString("RetrievedResources_Glossaries_Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string SettingsView_BrowseButton {
            get {
                return ResourceManager.GetString("SettingsView_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom name for this provider.
        /// </summary>
        public static string SettingsView_CustomName_Description {
            get {
                return ResourceManager.GetString("SettingsView_CustomName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your custom name here.
        /// </summary>
        public static string SettingsView_CustomName_Watermark {
            get {
                return ResourceManager.GetString("SettingsView_CustomName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do post-lookup find/replace.
        /// </summary>
        public static string SettingsView_PostLookup_Description {
            get {
                return ResourceManager.GetString("SettingsView_PostLookup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the location of the post-lookup file or browse.
        /// </summary>
        public static string SettingsView_PostLookup_WaterMark {
            get {
                return ResourceManager.GetString("SettingsView_PostLookup_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pre-lookup find/replace.
        /// </summary>
        public static string SettingsView_PreLookup_Description {
            get {
                return ResourceManager.GetString("SettingsView_PreLookup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the location of the pre-lookup file or browse.
        /// </summary>
        public static string SettingsView_PreLookup_WaterMark {
            get {
                return ResourceManager.GetString("SettingsView_PreLookup_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send draft and translated segments.
        /// </summary>
        public static string SettingsView_ResendDraft_Description {
            get {
                return ResourceManager.GetString("SettingsView_ResendDraft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not include tags in the translated segments.
        /// </summary>
        public static string SettingsView_TextOnly_Description {
            get {
                return ResourceManager.GetString("SettingsView_TextOnly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [segment already translated...source not re-sent].
        /// </summary>
        public static string TranslationLookupDraftNotResentMessage {
            get {
                return ResourceManager.GetString("TranslationLookupDraftNotResentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation provider URI not supported..
        /// </summary>
        public static string UriNotSupportedMessage {
            get {
                return ResourceManager.GetString("UriNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google Cloud API it is limited to 5000 characters per segment. Characters count: {0}.
        /// </summary>
        public static string V2Api_CharacterLimit {
            get {
                return ResourceManager.GetString("V2Api_CharacterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect to the service without an API Key..
        /// </summary>
        public static string Validation_ApiKey {
            get {
                return ResourceManager.GetString("Validation_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate the user with the ProjectID provided in the JSON file..
        /// </summary>
        public static string Validation_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Validation_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local path to the JSON file cannot be empty, please browse for your file from your machine..
        /// </summary>
        public static string Validation_EmptyJsonFilePath {
            get {
                return ResourceManager.GetString("Validation_EmptyJsonFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected glossary is no longer available..
        /// </summary>
        public static string Validation_Glossary_Invalid {
            get {
                return ResourceManager.GetString("Validation_Glossary_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project location can not be empty. Please select an option from the drop down menu..
        /// </summary>
        public static string Validation_Location_Empty {
            get {
                return ResourceManager.GetString("Validation_Location_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project location is invalid. This project is available only on the next location(s): {0}..
        /// </summary>
        public static string Validation_Location_Failed {
            get {
                return ResourceManager.GetString("Validation_Location_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON file could not be found, the file could be either renamed, moved or deleted, please browse again for you file..
        /// </summary>
        public static string Validation_MissingJsonFile {
            get {
                return ResourceManager.GetString("Validation_MissingJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model name is invalid, it might be misspelled or it doesn&apos;t exists..
        /// </summary>
        public static string Validation_ModelName_Invalid {
            get {
                return ResourceManager.GetString("Validation_ModelName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one file can be dropped to be used on the authentication process..
        /// </summary>
        public static string Validation_MultipleFiles {
            get {
                return ResourceManager.GetString("Validation_MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied, could not connect to the server using the provided credentials.
        /// </summary>
        public static string Validation_PermissionDenied {
            get {
                return ResourceManager.GetString("Validation_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProjectID can not be empty. Please write the ProjectID or browse for your file, if the JSON file contains it, the ProjectID will be completed automatically..
        /// </summary>
        public static string Validation_ProjectID_Empty {
            get {
                return ResourceManager.GetString("Validation_ProjectID_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProjectID was not correct. Please write the ProjectID or browse for your file, if the JSON file contains it, the ProjectID will be completed automatically..
        /// </summary>
        public static string Validation_ProjectID_Failed {
            get {
                return ResourceManager.GetString("Validation_ProjectID_Failed", resourceCulture);
            }
        }
    }
}
