//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.Legit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.Legit.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string BrowseForFilesDialogFilter {
            get {
                return ResourceManager.GetString("BrowseForFilesDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for source file(s)....
        /// </summary>
        internal static string BrowseForFilesDialogTitle {
            get {
                return ResourceManager.GetString("BrowseForFilesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string CompletedMessage {
            get {
                return ResourceManager.GetString("CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {0} ....
        /// </summary>
        internal static string ConvertingFileX {
            get {
                return ResourceManager.GetString("ConvertingFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed! Reason: {0}.
        /// </summary>
        internal static string FileConversionFailedDueTo {
            get {
                return ResourceManager.GetString("FileConversionFailedDueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion successful..
        /// </summary>
        internal static string FileConversionSuccessfull {
            get {
                return ResourceManager.GetString("FileConversionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trados Tools installation folder could not be found in the registry. Check your installation of client tools..
        /// </summary>
        internal static string InstallFolderNotFoundInRegistryText {
            get {
                return ResourceManager.GetString("InstallFolderNotFoundInRegistryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation folder not found.
        /// </summary>
        internal static string InstallFolderNotFoundInRegistryTitle {
            get {
                return ResourceManager.GetString("InstallFolderNotFoundInRegistryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trados Studio 2021 is not licensed on this computer. Activate it first before using this add-on..
        /// </summary>
        internal static string LicenseErrorMessage {
            get {
                return ResourceManager.GetString("LicenseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TM.
        /// </summary>
        internal static string MainForm_btnTM_Click_Select_TM {
            get {
                return ResourceManager.GetString("MainForm_btnTM_Click_Select_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM Files (*.tmw)|*.tmw.
        /// </summary>
        internal static string MainForm_btnTM_Click_TM_Files____tmw____tmw {
            get {
                return ResourceManager.GetString("MainForm_btnTM_Click_TM_Files____tmw____tmw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no source files selected for conversion. You must select at least one file..
        /// </summary>
        internal static string NoSourceFilesSelectedText {
            get {
                return ResourceManager.GetString("NoSourceFilesSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source filese selected.
        /// </summary>
        internal static string NoSourceFilesSelectedTitle {
            get {
                return ResourceManager.GetString("NoSourceFilesSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open target folder. There are no files selected for conversion..
        /// </summary>
        internal static string OpenTargetFolderMessageText {
            get {
                return ResourceManager.GetString("OpenTargetFolderMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open target folder.
        /// </summary>
        internal static string OpenTargetFolderMessageTitle {
            get {
                return ResourceManager.GetString("OpenTargetFolderMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string PrerequisitesProblemTitle {
            get {
                return ResourceManager.GetString("PrerequisitesProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdl.ttxit.log.txt.
        /// </summary>
        internal static string SaveLogDialogDefaultFileName {
            get {
                return ResourceManager.GetString("SaveLogDialogDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string SaveLogDialogFilter {
            get {
                return ResourceManager.GetString("SaveLogDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log to text file....
        /// </summary>
        internal static string SaveLogDialogTitle {
            get {
                return ResourceManager.GetString("SaveLogDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file was successfully saved..
        /// </summary>
        internal static string SaveLogSuccessMessageText {
            get {
                return ResourceManager.GetString("SaveLogSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log saved..
        /// </summary>
        internal static string SaveLogSuccessMessageTittle {
            get {
                return ResourceManager.GetString("SaveLogSuccessMessageTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} file(s) for conversion..
        /// </summary>
        internal static string SelectedXFilesForConversion {
            get {
                return ResourceManager.GetString("SelectedXFilesForConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language set to: {0} [ lcid = {1} ]..
        /// </summary>
        internal static string SourceLanguageSetTo {
            get {
                return ResourceManager.GetString("SourceLanguageSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL Trados 2007 needs to be installed to run this tool..
        /// </summary>
        internal static string T2007NotInstalledMessage {
            get {
                return ResourceManager.GetString("T2007NotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target language set to: {0} [ lcid = {1} ]..
        /// </summary>
        internal static string TargetLanguageSetTo {
            get {
                return ResourceManager.GetString("TargetLanguageSetTo", resourceCulture);
            }
        }
    }
}
