namespace Multilingual.XML.FileType.FileType.Settings.Entities
{
    public class UniqueEntitySetBuilder : EntitySetBuilder
    {

        protected override EntitySet CreateISOAMSAEntitySet()
        {
            EntityMapping[] mappings = new[]
             {
                new EntityMapping("DDotrahd", (char)0x2911, true),
                new EntityMapping("Darr", (char)0x21A1, true),
                new EntityMapping("Larr", (char)0x219E, true),
                new EntityMapping("Map", (char)0x2905, true),
                new EntityMapping("RBarr", (char)0x2910, true),
                new EntityMapping("Rarr", (char)0x21A0, true),
                new EntityMapping("Rarrtl", (char)0x2916, true),
                new EntityMapping("Uarr", (char)0x219F, true),
                new EntityMapping("Uarrocir", (char)0x2949, true),
                new EntityMapping("angzarr", (char)0x237C, true),
                new EntityMapping("cirmid", (char)0x2AEF, true),
                new EntityMapping("cudarrl", (char)0x2938, true),
                new EntityMapping("cudarrr", (char)0x2935, true),
                new EntityMapping("cularr", (char)0x21B6, true),
                new EntityMapping("cularrp", (char)0x293D, true),
                new EntityMapping("curarr", (char)0x21B7, true),
                new EntityMapping("curarrm", (char)0x293C, true),
                //duplicated new EntityMapping("dArr", (char)0x21D3, true),
                new EntityMapping("dHar", (char)0x2965, true),
                new EntityMapping("ddarr", (char)0x21CA, true),
                new EntityMapping("dfisht", (char)0x297F, true),
                new EntityMapping("dharl", (char)0x21C3, true),
                new EntityMapping("dharr", (char)0x21C2, true),
                new EntityMapping("duarr", (char)0x21F5, true),
                new EntityMapping("duhar", (char)0x296F, true),
                new EntityMapping("dzigrarr", (char)0x27FF, true),
                new EntityMapping("erarr", (char)0x2971, true),
                //duplicated new EntityMapping("hArr", (char)0x21D4, true),
                //duplicated new EntityMapping("harr", (char)0x2194, true),
                new EntityMapping("harrcir", (char)0x2948, true),
                new EntityMapping("harrw", (char)0x21AD, true),
                new EntityMapping("hoarr", (char)0x21FF, true),
                new EntityMapping("imof", (char)0x22B7, true),
                new EntityMapping("lAarr", (char)0x21DA, true),
                new EntityMapping("lAtail", (char)0x291B, true),
                new EntityMapping("lBarr", (char)0x290E, true),
                new EntityMapping("lHar", (char)0x2962, true),
                new EntityMapping("larrbfs", (char)0x291F, true),
                new EntityMapping("larrfs", (char)0x291D, true),
                new EntityMapping("larrhk", (char)0x21A9, true),
                new EntityMapping("larrlp", (char)0x21AB, true),
                new EntityMapping("larrpl", (char)0x2939, true),
                new EntityMapping("larrsim", (char)0x2973, true),
                new EntityMapping("larrtl", (char)0x21A2, true),
                new EntityMapping("latail", (char)0x2919, true),
                new EntityMapping("lbarr", (char)0x290C, true),
                new EntityMapping("ldca", (char)0x2936, true),
                new EntityMapping("ldrdhar", (char)0x2967, true),
                new EntityMapping("ldrushar", (char)0x294B, true),
                new EntityMapping("ldsh", (char)0x21B2, true),
                new EntityMapping("lfisht", (char)0x297C, true),
                new EntityMapping("lhard", (char)0x21BD, true),
                new EntityMapping("lharu", (char)0x21BC, true),
                new EntityMapping("lharul", (char)0x296A, true),
                new EntityMapping("llarr", (char)0x21C7, true),
                new EntityMapping("llhard", (char)0x296B, true),
                new EntityMapping("loarr", (char)0x21FD, true),
                new EntityMapping("lrarr", (char)0x21C6, true),
                new EntityMapping("lrhar", (char)0x21CB, true),
                new EntityMapping("lrhard", (char)0x296D, true),
                new EntityMapping("lsh", (char)0x21B0, true),
                new EntityMapping("lurdshar", (char)0x294A, true),
                new EntityMapping("luruhar", (char)0x2966, true),
                new EntityMapping("map", (char)0x21A6, true),
                new EntityMapping("midcir", (char)0x2AF0, true),
                new EntityMapping("mumap", (char)0x22B8, true),
                new EntityMapping("neArr", (char)0x21D7, true),
                new EntityMapping("nearhk", (char)0x2924, true),
                new EntityMapping("nearr", (char)0x2197, true),
                new EntityMapping("nesear", (char)0x2928, true),
                new EntityMapping("nhArr", (char)0x21CE, true),
                new EntityMapping("nharr", (char)0x21AE, true),
                new EntityMapping("nlArr", (char)0x21CD, true),
                new EntityMapping("nlarr", (char)0x219A, true),
                new EntityMapping("nrArr", (char)0x21CF, true),
                new EntityMapping("nrarr", (char)0x219B, true),
                new EntityMapping("nrarrc", (char)0x2933, false),
                new EntityMapping("nrarrw", (char)0x219D, false),
                new EntityMapping("nvHarr", (char)0x2904, true),
                new EntityMapping("nvlArr", (char)0x2902, true),
                new EntityMapping("nvrArr", (char)0x2903, true),
                new EntityMapping("nwArr", (char)0x21D6, true),
                new EntityMapping("nwarhk", (char)0x2923, true),
                new EntityMapping("nwarr", (char)0x2196, true),
                new EntityMapping("nwnear", (char)0x2927, true),
                new EntityMapping("olarr", (char)0x21BA, true),
                new EntityMapping("orarr", (char)0x21BB, true),
                new EntityMapping("origof", (char)0x22B6, true),
                new EntityMapping("rAarr", (char)0x21DB, true),
                new EntityMapping("rAtail", (char)0x291C, true),
                new EntityMapping("rBarr", (char)0x290F, true),
                new EntityMapping("rHar", (char)0x2964, true),
                new EntityMapping("rarrap", (char)0x2975, true),
                new EntityMapping("rarrbfs", (char)0x2920, true),
                new EntityMapping("rarrc", (char)0x2933, true),
                new EntityMapping("rarrfs", (char)0x291E, true),
                new EntityMapping("rarrhk", (char)0x21AA, true),
                new EntityMapping("rarrlp", (char)0x21AC, true),
                new EntityMapping("rarrpl", (char)0x2945, true),
                new EntityMapping("rarrsim", (char)0x2974, true),
                new EntityMapping("rarrtl", (char)0x21A3, true),
                new EntityMapping("rarrw", (char)0x219D, true),
                new EntityMapping("ratail", (char)0x291A, true),
                new EntityMapping("rbarr", (char)0x290D, true),
                new EntityMapping("rdca", (char)0x2937, true),
                new EntityMapping("rdldhar", (char)0x2969, true),
                new EntityMapping("rdsh", (char)0x21B3, true),
                new EntityMapping("rfisht", (char)0x297D, true),
                new EntityMapping("rhard", (char)0x21C1, true),
                new EntityMapping("rharu", (char)0x21C0, true),
                new EntityMapping("rharul", (char)0x296C, true),
                new EntityMapping("rlarr", (char)0x21C4, true),
                new EntityMapping("rlhar", (char)0x21CC, true),
                new EntityMapping("roarr", (char)0x21FE, true),
                new EntityMapping("rrarr", (char)0x21C9, true),
                new EntityMapping("rsh", (char)0x21B1, true),
                new EntityMapping("ruluhar", (char)0x2968, true),
                new EntityMapping("seArr", (char)0x21D8, true),
                new EntityMapping("searhk", (char)0x2925, true),
                new EntityMapping("searr", (char)0x2198, true),
                new EntityMapping("seswar", (char)0x2929, true),
                new EntityMapping("simrarr", (char)0x2972, true),
                //duplicated new EntityMapping("slarr", (char)0x2190),
                //duplicated new EntityMapping("srarr", (char)0x2192), 
                new EntityMapping("swArr", (char)0x21D9, true),
                new EntityMapping("swarhk", (char)0x2926, true),
                new EntityMapping("swarr", (char)0x2199, true),
                new EntityMapping("swnwar", (char)0x292A, true),
                //duplicated new EntityMapping("uArr", (char)0x21D1), 
                new EntityMapping("uHar", (char)0x2963, true),
                new EntityMapping("udarr", (char)0x21C5, true),
                new EntityMapping("udhar", (char)0x296E, true),
                new EntityMapping("ufisht", (char)0x297E, true),
                new EntityMapping("uharl", (char)0x21BF, true),
                new EntityMapping("uharr", (char)0x21BE, true),
                new EntityMapping("uuarr", (char)0x21C8, true),
                new EntityMapping("vArr", (char)0x21D5, true),
                new EntityMapping("varr", (char)0x2195, true),
                new EntityMapping("xhArr", (char)0x27FA, true),
                new EntityMapping("xharr", (char)0x27F7, true),
                new EntityMapping("xlArr", (char)0x27F8, true),
                new EntityMapping("xlarr", (char)0x27F5, true),
                new EntityMapping("xmap", (char)0x27FC, true),
                new EntityMapping("xrArr", (char)0x27F9, true),
                new EntityMapping("xrarr", (char)0x27F6, true),
                new EntityMapping("zigrarr", (char)0x21DD, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOAMSA.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOAMSBEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("Barwed", (char)0x2306, true),
                new EntityMapping("Cap", (char)0x22D2, true),
                new EntityMapping("Cup", (char)0x22D3, true),
                //duplicated new EntityMapping("Dagger", (char)0x2021, true),
                new EntityMapping("Otimes", (char)0x2A37, true),
                new EntityMapping("ac", (char)0x223E, true),
                new EntityMapping("acE", (char)0x223E, false),
                new EntityMapping("amalg", (char)0x2A3F, true),
                new EntityMapping("barvee", (char)0x22BD, true),
                new EntityMapping("barwed", (char)0x2305, true),
                new EntityMapping("bsolb", (char)0x29C5, true),
                new EntityMapping("capand", (char)0x2A44, true),
                new EntityMapping("capbrcup", (char)0x2A49, true),
                new EntityMapping("capcap", (char)0x2A4B, true),
                new EntityMapping("capcup", (char)0x2A47, true),
                new EntityMapping("capdot", (char)0x2A40, true),
                new EntityMapping("caps", (char)0x2229, false),
                new EntityMapping("ccaps", (char)0x2A4D, true),
                new EntityMapping("ccups", (char)0x2A4C, true),
                new EntityMapping("ccupssm", (char)0x2A50, true),
                new EntityMapping("coprod", (char)0x2210, true),
                new EntityMapping("cupbrcap", (char)0x2A48, true),
                new EntityMapping("cupcap", (char)0x2A46, true),
                new EntityMapping("cupcup", (char)0x2A4A, true),
                new EntityMapping("cupdot", (char)0x228D, true),
                new EntityMapping("cupor", (char)0x2A45, true),
                new EntityMapping("cups", (char)0x222A, false),
                new EntityMapping("cuvee", (char)0x22CE, true),
                new EntityMapping("cuwed", (char)0x22CF, true),
                //duplicated new EntityMapping("dagger", (char)0x2020, true),
                new EntityMapping("diam", (char)0x22C4, true),
                new EntityMapping("divonx", (char)0x22C7, true),
                new EntityMapping("eplus", (char)0x2A71, true),
                new EntityMapping("hercon", (char)0x22B9, true),
                new EntityMapping("intcal", (char)0x22BA, true),
                new EntityMapping("iprod", (char)0x2A3C, true),
                new EntityMapping("loplus", (char)0x2A2D, true),
                new EntityMapping("lotimes", (char)0x2A34, true),
                new EntityMapping("lthree", (char)0x22CB, true),
                new EntityMapping("ltimes", (char)0x22C9, true),
                new EntityMapping("midast", (char)0x002A, true),
                new EntityMapping("minusb", (char)0x229F, true),
                new EntityMapping("minusd", (char)0x2238, true),
                new EntityMapping("minusdu", (char)0x2A2A, true),
                new EntityMapping("ncap", (char)0x2A43, true),
                new EntityMapping("ncup", (char)0x2A42, true),
                new EntityMapping("oast", (char)0x229B, true),
                new EntityMapping("ocir", (char)0x229A, true),
                new EntityMapping("odash", (char)0x229D, true),
                new EntityMapping("odiv", (char)0x2A38, true),
                new EntityMapping("odot", (char)0x2299, true),
                new EntityMapping("odsold", (char)0x29BC, true),
                new EntityMapping("ofcir", (char)0x29BF, true),
                new EntityMapping("ogt", (char)0x29C1, true),
                new EntityMapping("ohbar", (char)0x29B5, true),
                new EntityMapping("olcir", (char)0x29BE, true),
                new EntityMapping("olt", (char)0x29C0, true),
                new EntityMapping("omid", (char)0x29B6, true),
                new EntityMapping("ominus", (char)0x2296, true),
                new EntityMapping("opar", (char)0x29B7, true),
                new EntityMapping("operp", (char)0x29B9, true),
                //duplicated new EntityMapping("oplus", (char)0x2295, true),
                new EntityMapping("osol", (char)0x2298, true),
                //duplicated new EntityMapping("otimes", (char)0x2297, true),
                new EntityMapping("otimesas", (char)0x2A36, true),
                new EntityMapping("ovbar", (char)0x233D, true),
                new EntityMapping("plusacir", (char)0x2A23, true),
                new EntityMapping("plusb", (char)0x229E, true),
                new EntityMapping("pluscir", (char)0x2A22, true),
                new EntityMapping("plusdo", (char)0x2214, true),
                new EntityMapping("plusdu", (char)0x2A25, true),
                new EntityMapping("pluse", (char)0x2A72, true),
                new EntityMapping("plussim", (char)0x2A26, true),
                new EntityMapping("plustwo", (char)0x2A27, true),
                //duplicated new EntityMapping("prod", (char)0x220F, true),
                new EntityMapping("race", (char)0x29DA, true),
                new EntityMapping("roplus", (char)0x2A2E, true),
                new EntityMapping("rotimes", (char)0x2A35, true),
                new EntityMapping("rthree", (char)0x22CC, true),
                new EntityMapping("rtimes", (char)0x22CA, true),
                //duplicated new EntityMapping("sdot", (char)0x22C5, true),
                new EntityMapping("sdotb", (char)0x22A1, true),
                new EntityMapping("setmn", (char)0x2216, true),
                new EntityMapping("simplus", (char)0x2A24, true),
                new EntityMapping("smashp", (char)0x2A33, true),
                new EntityMapping("solb", (char)0x29C4, true),
                new EntityMapping("sqcap", (char)0x2293, true),
                new EntityMapping("sqcaps", (char)0x2293, false),
                new EntityMapping("sqcup", (char)0x2294, true),
                new EntityMapping("sqcups", (char)0x2294, false),
                new EntityMapping("ssetmn", (char)0x2216, true),
                new EntityMapping("sstarf", (char)0x22C6, true),
                new EntityMapping("subdot", (char)0x2ABD, true),
                //duplicated new EntityMapping("sum", (char)0x2211, true),
                new EntityMapping("supdot", (char)0x2ABE, true),
                new EntityMapping("timesb", (char)0x22A0, true),
                new EntityMapping("timesbar", (char)0x2A31, true),
                new EntityMapping("timesd", (char)0x2A30, true),
                new EntityMapping("tridot", (char)0x25EC, true),
                new EntityMapping("triminus", (char)0x2A3A, true),
                new EntityMapping("triplus", (char)0x2A39, true),
                new EntityMapping("trisb", (char)0x29CD, true),
                new EntityMapping("tritime", (char)0x2A3B, true),
                new EntityMapping("uplus", (char)0x228E, true),
                new EntityMapping("veebar", (char)0x22BB, true),
                new EntityMapping("wedbar", (char)0x2A5F, true),
                new EntityMapping("wreath", (char)0x2240, true),
                new EntityMapping("xcap", (char)0x22C2, true),
                new EntityMapping("xcirc", (char)0x25EF, true),
                new EntityMapping("xcup", (char)0x22C3, true),
                new EntityMapping("xdtri", (char)0x25BD, true),
                new EntityMapping("xodot", (char)0x2A00, true),
                new EntityMapping("xoplus", (char)0x2A01, true),
                new EntityMapping("xotime", (char)0x2A02, true),
                new EntityMapping("xsqcup", (char)0x2A06, true),
                new EntityMapping("xuplus", (char)0x2A04, true),
                new EntityMapping("xutri", (char)0x25B3, true),
                new EntityMapping("xvee", (char)0x22C1, true),
                new EntityMapping("xwedge", (char)0x22C0, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOAMSB.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOAMSCEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("dlcorn", (char)0x231E, true),
                new EntityMapping("drcorn", (char)0x231F, true),
                new EntityMapping("gtlPar", (char)0x2995, true),
                new EntityMapping("langd", (char)0x2991, true),
                new EntityMapping("lbrke", (char)0x298B, true),
                new EntityMapping("lbrksld", (char)0x298F, true),
                new EntityMapping("lbrkslu", (char)0x298D, true),
                //duplicated new EntityMapping("lceil", (char)0x2308, true),
                //duplicated new EntityMapping("lfloor", (char)0x230A, true),
                new EntityMapping("lmoust", (char)0x23B0, true),
                new EntityMapping("lparlt", (char)0x2993, true),
                new EntityMapping("ltrPar", (char)0x2996, true),
                new EntityMapping("rangd", (char)0x2992, true),
                new EntityMapping("rbrke", (char)0x298C, true),
                new EntityMapping("rbrksld", (char)0x298E, true),
                new EntityMapping("rbrkslu", (char)0x2990, true),
                //duplicated new EntityMapping("rceil", (char)0x2309, true),
                //duplicated new EntityMapping("rfloor", (char)0x230B, true),
                new EntityMapping("rmoust", (char)0x23B1, true),
                new EntityMapping("rpargt", (char)0x2994, true),
                new EntityMapping("ulcorn", (char)0x231C, true),
                new EntityMapping("urcorn", (char)0x231D, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOAMSC.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOAMSOEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                //duplicated new EntityMapping("ang", (char)0x2220, true),
                new EntityMapping("ange", (char)0x29A4, true),
                new EntityMapping("angmsd", (char)0x2221, true),
                new EntityMapping("angmsdaa", (char)0x29A8, true),
                new EntityMapping("angmsdab", (char)0x29A9, true),
                new EntityMapping("angmsdac", (char)0x29AA, true),
                new EntityMapping("angmsdad", (char)0x29AB, true),
                new EntityMapping("angmsdae", (char)0x29AC, true),
                new EntityMapping("angmsdaf", (char)0x29AD, true),
                new EntityMapping("angmsdag", (char)0x29AE, true),
                new EntityMapping("angmsdah", (char)0x29AF, true),
                new EntityMapping("angrtvb", (char)0x22BE, true),
                new EntityMapping("angrtvbd", (char)0x299D, true),
                new EntityMapping("bbrk", (char)0x23B5, true),
                new EntityMapping("bbrktbrk", (char)0x23B6, true),
                new EntityMapping("bemptyv", (char)0x29B0, true),
                new EntityMapping("beth", (char)0x2136, true),
                new EntityMapping("boxbox", (char)0x29C9, true),
                new EntityMapping("bprime", (char)0x2035, true),
                new EntityMapping("bsemi", (char)0x204F, true),
                new EntityMapping("cemptyv", (char)0x29B2, true),
                new EntityMapping("cirE", (char)0x29C3, true),
                new EntityMapping("cirscir", (char)0x29C2, true),
                new EntityMapping("comp", (char)0x2201, true),
                new EntityMapping("daleth", (char)0x2138, true),
                new EntityMapping("demptyv", (char)0x29B1, true),
                new EntityMapping("ell", (char)0x2113, true),
                //duplicated new EntityMapping("empty", (char)0x2205, true),
                new EntityMapping("emptyv", (char)0x2205, true),
                new EntityMapping("gimel", (char)0x2137, true),
                new EntityMapping("iiota", (char)0x2129, true),
                //duplicated new EntityMapping("image", (char)0x2111, true),
                new EntityMapping("imath", (char)0x0131, true),
                new EntityMapping("jmath", (char)0x0237, true),
                new EntityMapping("laemptyv", (char)0x29B4, true),
                new EntityMapping("lltri", (char)0x25FA, true),
                new EntityMapping("lrtri", (char)0x22BF, true),
                new EntityMapping("mho", (char)0x2127, true),
                new EntityMapping("nang", (char)0x2220, false),
                new EntityMapping("nexist", (char)0x2204, true),
                new EntityMapping("oS", (char)0x24C8, true),
                new EntityMapping("planck", (char)0x210F, true),
                new EntityMapping("plankv", (char)0x210F, true),
                new EntityMapping("raemptyv", (char)0x29B3, true),
                new EntityMapping("range", (char)0x29A5, true),
                //duplicated new EntityMapping("real", (char)0x211C, true),
                new EntityMapping("tbrk", (char)0x23B4, true),
                new EntityMapping("trpezium", (char)0x23E2, true),
                new EntityMapping("ultri", (char)0x25F8, true),
                new EntityMapping("urtri", (char)0x25F9, true),
                new EntityMapping("vzigzag", (char)0x299A, true),
                //duplicated new EntityMapping("weierp", (char)0x2118, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOAMSO.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOAMSREntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("Barv", (char)0x2AE7, true),
                new EntityMapping("Colon", (char)0x2237, true),
                new EntityMapping("Colone", (char)0x2A74, true),
                new EntityMapping("Dashv", (char)0x2AE4, true),
                new EntityMapping("Esim", (char)0x2A73, true),
                new EntityMapping("Gg", (char)0x22D9, true),
                new EntityMapping("Gt", (char)0x226B, true),
                new EntityMapping("Ll", (char)0x22D8, true),
                new EntityMapping("Lt", (char)0x226A, true),
                new EntityMapping("Pr", (char)0x2ABB, true),
                new EntityMapping("Sc", (char)0x2ABC, true),
                new EntityMapping("Sub", (char)0x22D0, true),
                new EntityMapping("Sup", (char)0x22D1, true),
                new EntityMapping("VDash", (char)0x22AB, true),
                new EntityMapping("Vbar", (char)0x2AEB, true),
                new EntityMapping("Vdash", (char)0x22A9, true),
                new EntityMapping("Vdashl", (char)0x2AE6, true),
                new EntityMapping("Vvdash", (char)0x22AA, true),
                new EntityMapping("apE", (char)0x2A70, true),
                new EntityMapping("ape", (char)0x224A, true),
                new EntityMapping("apid", (char)0x224B, true),
                //duplicated new EntityMapping("asymp", (char)0x2248, true),
                new EntityMapping("bcong", (char)0x224C, true),
                new EntityMapping("bepsi", (char)0x03F6, true),
                new EntityMapping("bowtie", (char)0x22C8, true),
                new EntityMapping("bsim", (char)0x223D, true),
                new EntityMapping("bsime", (char)0x22CD, true),
                new EntityMapping("bsolhsub", (char)0x2282, false),
                new EntityMapping("bump", (char)0x224E, true),
                new EntityMapping("bumpE", (char)0x2AAE, true),
                new EntityMapping("bumpe", (char)0x224F, true),
                new EntityMapping("cire", (char)0x2257, true),
                new EntityMapping("colone", (char)0x2254, true),
                new EntityMapping("congdot", (char)0x2A6D, true),
                new EntityMapping("csub", (char)0x2ACF, true),
                new EntityMapping("csube", (char)0x2AD1, true),
                new EntityMapping("csup", (char)0x2AD0, true),
                new EntityMapping("csupe", (char)0x2AD2, true),
                new EntityMapping("cuepr", (char)0x22DE, true),
                new EntityMapping("cuesc", (char)0x22DF, true),
                new EntityMapping("dashv", (char)0x22A3, true),
                new EntityMapping("eDDot", (char)0x2A77, true),
                new EntityMapping("eDot", (char)0x2251, true),
                new EntityMapping("easter", (char)0x2A6E, true),
                new EntityMapping("ecir", (char)0x2256, true),
                new EntityMapping("ecolon", (char)0x2255, true),
                new EntityMapping("efDot", (char)0x2252, true),
                new EntityMapping("eg", (char)0x2A9A, true),
                new EntityMapping("egs", (char)0x2A96, true),
                new EntityMapping("egsdot", (char)0x2A98, true),
                new EntityMapping("el", (char)0x2A99, true),
                new EntityMapping("els", (char)0x2A95, true),
                new EntityMapping("elsdot", (char)0x2A97, true),
                new EntityMapping("equest", (char)0x225F, true),
                new EntityMapping("equivDD", (char)0x2A78, true),
                new EntityMapping("erDot", (char)0x2253, true),
                new EntityMapping("esdot", (char)0x2250, true),
                new EntityMapping("esim", (char)0x2242, true),
                new EntityMapping("fork", (char)0x22D4, true),
                new EntityMapping("forkv", (char)0x2AD9, true),
                new EntityMapping("frown", (char)0x2322, true),
                new EntityMapping("gE", (char)0x2267, true),
                new EntityMapping("gEl", (char)0x2A8C, true),
                new EntityMapping("gap", (char)0x2A86, true),
                new EntityMapping("gel", (char)0x22DB, true),
                new EntityMapping("ges", (char)0x2A7E, true),
                new EntityMapping("gescc", (char)0x2AA9, true),
                new EntityMapping("gesdot", (char)0x2A80, true),
                new EntityMapping("gesdoto", (char)0x2A82, true),
                new EntityMapping("gesdotol", (char)0x2A84, true),
                new EntityMapping("gesl", (char)0x22DB, false),
                new EntityMapping("gesles", (char)0x2A94, true),
                new EntityMapping("gl", (char)0x2277, true),
                new EntityMapping("glE", (char)0x2A92, true),
                new EntityMapping("gla", (char)0x2AA5, true),
                new EntityMapping("glj", (char)0x2AA4, true),
                new EntityMapping("gsim", (char)0x2273, true),
                new EntityMapping("gsime", (char)0x2A8E, true),
                new EntityMapping("gsiml", (char)0x2A90, true),
                new EntityMapping("gtcc", (char)0x2AA7, true),
                new EntityMapping("gtcir", (char)0x2A7A, true),
                new EntityMapping("gtdot", (char)0x22D7, true),
                new EntityMapping("gtquest", (char)0x2A7C, true),
                new EntityMapping("gtrarr", (char)0x2978, true),
                new EntityMapping("homtht", (char)0x223B, true),
                new EntityMapping("lE", (char)0x2266, true),
                new EntityMapping("lEg", (char)0x2A8B, true),
                new EntityMapping("lap", (char)0x2A85, true),
                new EntityMapping("lat", (char)0x2AAB, true),
                new EntityMapping("late", (char)0x2AAD, true),
                new EntityMapping("lates", (char)0x2AAD, false),
                new EntityMapping("leg", (char)0x22DA, true),
                new EntityMapping("les", (char)0x2A7D, true),
                new EntityMapping("lescc", (char)0x2AA8, true),
                new EntityMapping("lesdot", (char)0x2A7F, true),
                new EntityMapping("lesdoto", (char)0x2A81, true),
                new EntityMapping("lesdotor", (char)0x2A83, true),
                new EntityMapping("lesg", (char)0x22DA, false),
                new EntityMapping("lesges", (char)0x2A93, true),
                new EntityMapping("lg", (char)0x2276, true),
                new EntityMapping("lgE", (char)0x2A91, true),
                new EntityMapping("lsim", (char)0x2272, true),
                new EntityMapping("lsime", (char)0x2A8D, true),
                new EntityMapping("lsimg", (char)0x2A8F, true),
                new EntityMapping("ltcc", (char)0x2AA6, true),
                new EntityMapping("ltcir", (char)0x2A79, true),
                new EntityMapping("ltdot", (char)0x22D6, true),
                new EntityMapping("ltlarr", (char)0x2976, true),
                new EntityMapping("ltquest", (char)0x2A7B, true),
                new EntityMapping("ltrie", (char)0x22B4, true),
                new EntityMapping("mDDot", (char)0x223A, true),
                new EntityMapping("mcomma", (char)0x2A29, true),
                new EntityMapping("mid", (char)0x2223, true),
                new EntityMapping("mlcp", (char)0x2ADB, true),
                new EntityMapping("models", (char)0x22A7, true),
                new EntityMapping("mstpos", (char)0x223E, true),
                new EntityMapping("pr", (char)0x227A, true),
                new EntityMapping("prE", (char)0x2AB3, true),
                new EntityMapping("prap", (char)0x2AB7, true),
                new EntityMapping("prcue", (char)0x227C, true),
                new EntityMapping("pre", (char)0x2AAF, true),
                new EntityMapping("prsim", (char)0x227E, true),
                new EntityMapping("prurel", (char)0x22B0, true),
                new EntityMapping("ratio", (char)0x2236, true),
                new EntityMapping("rtrie", (char)0x22B5, true),
                new EntityMapping("rtriltri", (char)0x29CE, true),
                new EntityMapping("sc", (char)0x227B, true),
                new EntityMapping("scE", (char)0x2AB4, true),
                new EntityMapping("scap", (char)0x2AB8, true),
                new EntityMapping("sccue", (char)0x227D, true),
                new EntityMapping("sce", (char)0x2AB0, true),
                new EntityMapping("scsim", (char)0x227F, true),
                new EntityMapping("sdote", (char)0x2A66, true),
                new EntityMapping("sfrown", (char)0x2322, true),
                new EntityMapping("simg", (char)0x2A9E, true),
                new EntityMapping("simgE", (char)0x2AA0, true),
                new EntityMapping("siml", (char)0x2A9D, true),
                new EntityMapping("simlE", (char)0x2A9F, true),
                new EntityMapping("smid", (char)0x2223, true),
                new EntityMapping("smile", (char)0x2323, true),
                new EntityMapping("smt", (char)0x2AAA, true),
                new EntityMapping("smte", (char)0x2AAC, true),
                new EntityMapping("smtes", (char)0x2AAC, false),
                new EntityMapping("spar", (char)0x2225, true),
                new EntityMapping("sqsub", (char)0x228F, true),
                new EntityMapping("sqsube", (char)0x2291, true),
                new EntityMapping("sqsup", (char)0x2290, true),
                new EntityMapping("sqsupe", (char)0x2292, true),
                new EntityMapping("ssmile", (char)0x2323, true),
                new EntityMapping("subE", (char)0x2AC5, true),
                new EntityMapping("subedot", (char)0x2AC3, true),
                new EntityMapping("submult", (char)0x2AC1, true),
                new EntityMapping("subplus", (char)0x2ABF, true),
                new EntityMapping("subrarr", (char)0x2979, true),
                new EntityMapping("subsim", (char)0x2AC7, true),
                new EntityMapping("subsub", (char)0x2AD5, true),
                new EntityMapping("subsup", (char)0x2AD3, true),
                new EntityMapping("supE", (char)0x2AC6, true),
                new EntityMapping("supdsub", (char)0x2AD8, true),
                new EntityMapping("supedot", (char)0x2AC4, true),
                new EntityMapping("suphsol", (char)0x2283, false),
                new EntityMapping("suphsub", (char)0x2AD7, true),
                new EntityMapping("suplarr", (char)0x297B, true),
                new EntityMapping("supmult", (char)0x2AC2, true),
                new EntityMapping("supplus", (char)0x2AC0, true),
                new EntityMapping("supsim", (char)0x2AC8, true),
                new EntityMapping("supsub", (char)0x2AD4, true),
                new EntityMapping("supsup", (char)0x2AD6, true),
                new EntityMapping("thkap", (char)0x2248, true),
                new EntityMapping("thksim", (char)0x223C, true),
                new EntityMapping("topfork", (char)0x2ADA, true),
                new EntityMapping("trie", (char)0x225C, true),
                new EntityMapping("twixt", (char)0x226C, true),
                new EntityMapping("vBar", (char)0x2AE8, true),
                new EntityMapping("vBarv", (char)0x2AE9, true),
                new EntityMapping("vDash", (char)0x22A8, true),
                new EntityMapping("vdash", (char)0x22A2, true),
                new EntityMapping("vltri", (char)0x22B2, true),
                new EntityMapping("vprop", (char)0x221D, true),
                new EntityMapping("vrtri", (char)0x22B3, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOAMSR.ToString();
            return eSet;
        }

        protected override EntitySet CreateISODIAEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("acute", (char)0x00B4, true),
                new EntityMapping("breve", (char)0x02D8, true),
                new EntityMapping("caron", (char)0x02C7, true),
                new EntityMapping("cedil", (char)0x00B8, true),
                //duplicated new EntityMapping("circ", (char)0x02C6, true),
                new EntityMapping("dblac", (char)0x02DD, true),
                new EntityMapping("die", (char)0x00A8, true),
                new EntityMapping("dot", (char)0x02D9, true),
                new EntityMapping("grave", (char)0x0060, true),
                new EntityMapping("macr", (char)0x00AF, true),
                new EntityMapping("ogon", (char)0x02DB, true),
                new EntityMapping("ring", (char)0x02DA, true),
                //duplicated new EntityMapping("tilde", (char)0x02DC, true),
                new EntityMapping("uml", (char)0x00A8, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISODIA.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOGRK3EntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                //duplicated new EntityMapping("alpha", (char)0x03B1, true),
                //duplicated new EntityMapping("beta", (char)0x03B2, true),
                //duplicated new EntityMapping("chi", (char)0x03C7, true),
                //duplicated new EntityMapping("Delta", (char)0x0394, true),
                //duplicated new EntityMapping("delta", (char)0x03B4, true),
                new EntityMapping("epsi", (char)0x03F5, true),
                new EntityMapping("epsiv", (char)0x03B5, true),
                //duplicated new EntityMapping("eta", (char)0x03B7, true),
                //duplicated new EntityMapping("Gamma", (char)0x0393, true),
                //duplicated new EntityMapping("gamma", (char)0x03B3, true),
                new EntityMapping("Gammad", (char)0x03DC, true),
                new EntityMapping("gammad", (char)0x03DD, true),
                //duplicated new EntityMapping("iota", (char)0x03B9, true),
                //duplicated new EntityMapping("kappa", (char)0x03BA, true),
                new EntityMapping("kappav", (char)0x03F0, true),
                //duplicated new EntityMapping("Lambda", (char)0x039B, true),
                //duplicated new EntityMapping("lambda", (char)0x03BB, true),
                //duplicated new EntityMapping("mu", (char)0x03BC, true),
                //duplicated new EntityMapping("nu", (char)0x03BD, true),
                //duplicated new EntityMapping("Omega", (char)0x03A9, true),
                //duplicated new EntityMapping("omega", (char)0x03C9, true),
                //duplicated new EntityMapping("omicron", (char)0x03BE, true),
                //duplicated new EntityMapping("Phi", (char)0x03A6, true),
                //duplicated new EntityMapping("phi", (char)0x03D5, true),
                new EntityMapping("phiv", (char)0x03C6, true),
                //duplicated new EntityMapping("Pi", (char)0x03A0, true),
                //duplicated new EntityMapping("pi", (char)0x03C0, true),
                //duplicated new EntityMapping("piv", (char)0x03D6, true),
                //duplicated new EntityMapping("Psi", (char)0x03A8, true),
                //duplicated new EntityMapping("psi", (char)0x03C8, true),
                //duplicated new EntityMapping("rho", (char)0x03C1, true),
                new EntityMapping("rhov", (char)0x03F1, true),
                //duplicated new EntityMapping("Sigma", (char)0x03A3, true),
                //duplicated new EntityMapping("sigma", (char)0x03C3, true),
                new EntityMapping("sigmav", (char)0x03C2, true),
                //duplicated new EntityMapping("tau", (char)0x03C4, true),
                //duplicated new EntityMapping("Theta", (char)0x0398, true),
                //duplicated new EntityMapping("theta", (char)0x03B8, true),
                new EntityMapping("thetav", (char)0x03D1, true),
                new EntityMapping("Upsi", (char)0x03D2, true),
                new EntityMapping("upsi", (char)0x03C5, true),
                //duplicated new EntityMapping("Xi", (char)0x039E, true),
                //duplicated new EntityMapping("xi", (char)0x03BE, true),
                //duplicated new EntityMapping("zeta",(char)0x03B6, true)
                        };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOGRK3.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOLAT2EntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("Abreve", (char)0x0102, true),
                new EntityMapping("Amacr", (char)0x0100, true),
                new EntityMapping("Aogon", (char)0x0104, true),
                new EntityMapping("Cacute", (char)0x0106, true),
                new EntityMapping("Ccaron", (char)0x010C, true),
                new EntityMapping("Ccirc", (char)0x0108, true),
                new EntityMapping("Cdot", (char)0x010A, true),
                new EntityMapping("Dcaron", (char)0x010E, true),
                new EntityMapping("Dstrok", (char)0x0110, true),
                new EntityMapping("ENG", (char)0x014A, true),
                new EntityMapping("Ecaron", (char)0x011A, true),
                new EntityMapping("Edot", (char)0x0116, true),
                new EntityMapping("Emacr", (char)0x0112, true),
                new EntityMapping("Eogon", (char)0x0118, true),
                new EntityMapping("Gbreve", (char)0x011E, true),
                new EntityMapping("Gcedil", (char)0x0122, true),
                new EntityMapping("Gcirc", (char)0x011C, true),
                new EntityMapping("Gdot", (char)0x0120, true),
                new EntityMapping("Hcirc", (char)0x0124, true),
                new EntityMapping("Hstrok", (char)0x0126, true),
                new EntityMapping("IJlig", (char)0x0132, true),
                new EntityMapping("Idot", (char)0x0130, true),
                new EntityMapping("Imacr", (char)0x012A, true),
                new EntityMapping("Iogon", (char)0x012E, true),
                new EntityMapping("Itilde", (char)0x0128, true),
                new EntityMapping("Jcirc", (char)0x0134, true),
                new EntityMapping("Kcedil", (char)0x0136, true),
                new EntityMapping("Lacute", (char)0x0139, true),
                new EntityMapping("Lcaron", (char)0x013D, true),
                new EntityMapping("Lcedil", (char)0x013B, true),
                new EntityMapping("Lmidot", (char)0x013F, true),
                new EntityMapping("Lstrok", (char)0x0141, true),
                new EntityMapping("Nacute", (char)0x0143, true),
                new EntityMapping("Ncaron", (char)0x0147, true),
                new EntityMapping("Ncedil", (char)0x0145, true),
                //duplicated new EntityMapping("OElig", (char)0x0152, true),
                new EntityMapping("Odblac", (char)0x0150, true),
                new EntityMapping("Omacr", (char)0x014C, true),
                new EntityMapping("Racute", (char)0x0154, true),
                new EntityMapping("Rcaron", (char)0x0158, true),
                new EntityMapping("Rcedil", (char)0x0156, true),
                new EntityMapping("Sacute", (char)0x015A, true),
                //duplicated new EntityMapping("Scaron", (char)0x0160, true),
                new EntityMapping("Scedil", (char)0x015E, true),
                new EntityMapping("Scirc", (char)0x015C, true),
                new EntityMapping("Tcaron", (char)0x0164, true),
                new EntityMapping("Tcedil", (char)0x0162, true),
                new EntityMapping("Tstrok", (char)0x0166, true),
                new EntityMapping("Ubreve", (char)0x016C, true),
                new EntityMapping("Udblac", (char)0x0170, true),
                new EntityMapping("Umacr", (char)0x016A, true),
                new EntityMapping("Uogon", (char)0x0172, true),
                new EntityMapping("Uring", (char)0x016E, true),
                new EntityMapping("Utilde", (char)0x0168, true),
                new EntityMapping("Wcirc", (char)0x0174, true),
                new EntityMapping("Ycirc", (char)0x0176, true),
                //duplicated new EntityMapping("Yuml", (char)0x0178, true),
                new EntityMapping("Zacute", (char)0x0179, true),
                new EntityMapping("Zcaron", (char)0x017D, true),
                new EntityMapping("Zdot", (char)0x017B, true),
                new EntityMapping("abreve", (char)0x0103, true),
                new EntityMapping("amacr", (char)0x0101, true),
                new EntityMapping("aogon", (char)0x0105, true),
                new EntityMapping("cacute", (char)0x0107, true),
                new EntityMapping("ccaron", (char)0x010D, true),
                new EntityMapping("ccirc", (char)0x0109, true),
                new EntityMapping("cdot", (char)0x010B, true),
                new EntityMapping("dcaron", (char)0x010F, true),
                new EntityMapping("dstrok", (char)0x0111, true),
                new EntityMapping("ecaron", (char)0x011B, true),
                new EntityMapping("edot", (char)0x0117, true),
                new EntityMapping("emacr", (char)0x0113, true),
                new EntityMapping("eng", (char)0x014B, true),
                new EntityMapping("eogon", (char)0x0119, true),
                new EntityMapping("gacute", (char)0x01F5, true),
                new EntityMapping("gbreve", (char)0x011F, true),
                new EntityMapping("gcirc", (char)0x011D, true),
                new EntityMapping("gdot", (char)0x0121, true),
                new EntityMapping("hcirc", (char)0x0125, true),
                new EntityMapping("hstrok", (char)0x0127, true),
                new EntityMapping("ijlig", (char)0x0133, true),
                new EntityMapping("imacr", (char)0x012B, true),
                new EntityMapping("inodot", (char)0x0131, true),
                new EntityMapping("iogon", (char)0x012F, true),
                new EntityMapping("itilde", (char)0x0129, true),
                new EntityMapping("jcirc", (char)0x0135, true),
                new EntityMapping("kcedil", (char)0x0137, true),
                new EntityMapping("kgreen", (char)0x0138, true),
                new EntityMapping("lacute", (char)0x013A, true),
                new EntityMapping("lcaron", (char)0x013E, true),
                new EntityMapping("lcedil", (char)0x013C, true),
                new EntityMapping("lmidot", (char)0x0140, true),
                new EntityMapping("lstrok", (char)0x0142, true),
                new EntityMapping("nacute", (char)0x0144, true),
                new EntityMapping("napos", (char)0x0149, true),
                new EntityMapping("ncaron", (char)0x0148, true),
                new EntityMapping("ncedil", (char)0x0146, true),
                new EntityMapping("odblac", (char)0x0151, true),
                //duplicated new EntityMapping("oelig", (char)0x0153, true),
                new EntityMapping("omacr", (char)0x014D, true),
                new EntityMapping("racute", (char)0x0155, true),
                //duplicated new EntityMapping("rcaron", (char)0x0159, true),
                new EntityMapping("rcedil", (char)0x0157, true),
                new EntityMapping("sacute", (char)0x015B, true),
                //duplicated new EntityMapping("scaron", (char)0x0161, true),
                new EntityMapping("scedil", (char)0x015F, true),
                new EntityMapping("scirc", (char)0x015D, true),
                new EntityMapping("tcaron", (char)0x0165, true),
                new EntityMapping("tcedil", (char)0x0163, true),
                new EntityMapping("tstrok", (char)0x0167, true),
                new EntityMapping("ubreve", (char)0x016D, true),
                new EntityMapping("udblac", (char)0x0171, true),
                new EntityMapping("umacr", (char)0x016B, true),
                new EntityMapping("uogon", (char)0x0173, true),
                new EntityMapping("uring", (char)0x016F, true),
                new EntityMapping("utilde", (char)0x0169, true),
                new EntityMapping("wcirc", (char)0x0175, true),
                new EntityMapping("ycirc", (char)0x0177, true),
                new EntityMapping("zacute", (char)0x017A, true),
                new EntityMapping("zcaron", (char)0x017E, true),
                new EntityMapping("zdot", (char)0x017C, true)

            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOLAT2.ToString();
            return eSet;
        }


        protected override EntitySet CreateISONUMEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                //duplicated new EntityMapping("amp", (char)0x0026, true),
                new EntityMapping("apos", (char)0x0027, true, true),
                new EntityMapping("ast", (char)0x002A, true),
                new EntityMapping("brvbar", (char)0x00A6, true),
                new EntityMapping("bsol", (char)0x005C, true),
                new EntityMapping("cent", (char)0x00A2, true),
                new EntityMapping("colon", (char)0x003A, true),
                new EntityMapping("comma", (char)0x002C, true),
                new EntityMapping("commat", (char)0x0040, true),
                new EntityMapping("copy", (char)0x00A9, true),
                new EntityMapping("curren", (char)0x00A4, true),
                //duplicated  new EntityMapping("darr", (char)0x2193, true),
                new EntityMapping("deg", (char)0x00B0, true),
                new EntityMapping("divide", (char)0x00F7, true),
                new EntityMapping("dollar", (char)0x0024, true),
                new EntityMapping("equals", (char)0x003D, true),
                new EntityMapping("excl", (char)0x0021, true),
                new EntityMapping("frac12", (char)0x00BD, true),
                new EntityMapping("frac14", (char)0x00BC, true),
                new EntityMapping("frac18", (char)0x215B, true),
                new EntityMapping("frac34", (char)0x00BE, true),
                new EntityMapping("frac38", (char)0x215C, true),
                new EntityMapping("frac58", (char)0x215D, true),
                new EntityMapping("frac78", (char)0x215E, true),
                //duplicated new EntityMapping("gt", (char)0x003E, true),
                new EntityMapping("half", (char)0x00BD, true),
                new EntityMapping("horbar", (char)0x2015, true),
                new EntityMapping("hyphen", (char)0x2010, true),
                new EntityMapping("iexcl", (char)0x00A1, true),
                new EntityMapping("iquest", (char)0x00BF, true),
                new EntityMapping("laquo", (char)0x00AB, true),
                //duplicated new EntityMapping("larr", (char)0x2190, true),
                new EntityMapping("lcub", (char)0x007B, true),
                //duplicated new EntityMapping("ldquo", (char)0x201C, true),
                new EntityMapping("lowbar", (char)0x005F, true),
                new EntityMapping("lpar", (char)0x0028, true),
                new EntityMapping("lsqb", (char)0x005B, true),
                //duplicated new EntityMapping("lsquo", (char)0x2018, true),
                //duplicated new EntityMapping("lt", (char)0x003C, true),
                new EntityMapping("micro", (char)0x00B5, true),
                new EntityMapping("middot", (char)0x00B7, true),
                //duplicated  new EntityMapping("nbsp", (char)0x00A0, true),
                new EntityMapping("not", (char)0x00AC, true),
                new EntityMapping("num", (char)0x0023, true),
                new EntityMapping("ohm", (char)0x2126, true),
                new EntityMapping("ordf", (char)0x00AA, true),
                new EntityMapping("ordm", (char)0x00BA, true),
                new EntityMapping("para", (char)0x00B6, true),
                new EntityMapping("percnt", (char)0x0025, true),
                new EntityMapping("period", (char)0x002E, true),
                new EntityMapping("plus", (char)0x002B, true),
                new EntityMapping("plusmn", (char)0x00B1, true),
                new EntityMapping("pound", (char)0x00A3, true),
                new EntityMapping("quest", (char)0x003F, true),
                //duplicated new EntityMapping("quot", (char)0x0022, true),
                new EntityMapping("raquo", (char)0x00BB, true),
                //duplicated new EntityMapping("rarr", (char)0x2192, true),
                new EntityMapping("rcub", (char)0x007D, true),
                //duplicated new EntityMapping("rdquo", (char)0x201D, true),
                new EntityMapping("reg", (char)0x00AE, true),
                new EntityMapping("rpar", (char)0x0029, true),
                new EntityMapping("rsqb", (char)0x005D, true),
                //duplicated new EntityMapping("rsquo", (char)0x2019, true),
                new EntityMapping("sect", (char)0x00A7, true),
                new EntityMapping("semi", (char)0x003B, true),
                new EntityMapping("shy", (char)0x00AD, true),
                new EntityMapping("sol", (char)0x002F, true),
                new EntityMapping("sung", (char)0x266A, true),
                new EntityMapping("sup1", (char)0x00B9, true),
                new EntityMapping("sup2", (char)0x00B2, true),
                new EntityMapping("sup3", (char)0x00B3, true),
                new EntityMapping("times", (char)0x00D7, true),
                //duplicated new EntityMapping("trade", (char)0x2122, true),
                //duplicated new EntityMapping("uarr", (char)0x2191, true),
                new EntityMapping("verbar", (char)0x007C, true),
                new EntityMapping("yen", (char)0x00A5, true)

            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISONUM.ToString();
            return eSet;
        }


        protected override EntitySet CreateISOPUBEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                //duplicated new EntityMapping("Dagger", (char)0x2021, true),
                new EntityMapping("blank", (char)0x2423, true),
                new EntityMapping("blk12", (char)0x2592, true),
                new EntityMapping("blk14", (char)0x2591, true),
                new EntityMapping("blk34", (char)0x2593, true),
                new EntityMapping("block", (char)0x2588, true),
                //duplicated new EntityMapping("bull", (char)0x2022, true),
                new EntityMapping("caret", (char)0x2041, true),
                new EntityMapping("check", (char)0x2713, true),
                new EntityMapping("cir", (char)0x25CB, true),
                //duplicated new EntityMapping("clubs", (char)0x2663, true),
                new EntityMapping("copysr", (char)0x2117, true),
                new EntityMapping("cross", (char)0x2717, true),
                //duplicated new EntityMapping("dagger", (char)0x2020, true),
                new EntityMapping("dash", (char)0x2010, true),
                //duplicated new EntityMapping("diams", (char)0x2666, true),
                new EntityMapping("dlcrop", (char)0x230D, true),
                new EntityMapping("drcrop", (char)0x230C, true),
                new EntityMapping("dtri", (char)0x25BF, true),
                new EntityMapping("dtrif", (char)0x25BE, true),
                //duplicated new EntityMapping("emsp", (char)0x2003, true),
                new EntityMapping("emsp13", (char)0x2004, true),
                new EntityMapping("emsp14", (char)0x2005, true),
                //duplicated new EntityMapping("ensp", (char)0x2002, true),
                new EntityMapping("female", (char)0x2640, true),
                new EntityMapping("ffilig", (char)0xFB03, true),
                new EntityMapping("fflig", (char)0xFB00, true),
                new EntityMapping("ffllig", (char)0xFB04, true),
                new EntityMapping("filig", (char)0xFB01, true),
                new EntityMapping("fjlig", (char)0x0066, false),
                new EntityMapping("flat", (char)0x266D, true),
                new EntityMapping("fllig", (char)0xFB02, true),
                new EntityMapping("frac13", (char)0x2153, true),
                new EntityMapping("frac15", (char)0x2155, true),
                new EntityMapping("frac16", (char)0x2159, true),
                new EntityMapping("frac23", (char)0x2154, true),
                new EntityMapping("frac25", (char)0x2156, true),
                new EntityMapping("frac35", (char)0x2157, true),
                new EntityMapping("frac45", (char)0x2158, true),
                new EntityMapping("frac56", (char)0x215A, true),
                new EntityMapping("hairsp", (char)0x200A, true),
                //duplicated new EntityMapping("hearts", (char)0x2665, true),
                //duplicated new EntityMapping("hellip", (char)0x2026, true),
                new EntityMapping("hybull", (char)0x2043, true),
                new EntityMapping("incare", (char)0x2105, true),
                new EntityMapping("ldquor", (char)0x201E, true),
                new EntityMapping("lhblk", (char)0x2584, true),
                //duplicated new EntityMapping("loz", (char)0x25CA, true),
                new EntityMapping("lozf", (char)0x29EB, true),
                new EntityMapping("lsquor", (char)0x201A, true),
                new EntityMapping("ltri", (char)0x25C3, true),
                new EntityMapping("ltrif", (char)0x25C2, true),
                new EntityMapping("male", (char)0x2642, true),
                new EntityMapping("malt", (char)0x2720, true),
                new EntityMapping("marker", (char)0x25AE, true),
                //duplicated new EntityMapping("mdash", (char)0x2014, true),
                new EntityMapping("mldr", (char)0x2026, true),
                new EntityMapping("natur", (char)0x266E, true),
                //duplicated new EntityMapping("ndash", (char)0x2013, true),
                new EntityMapping("nldr", (char)0x2025, true),
                new EntityMapping("numsp", (char)0x2007, true),
                new EntityMapping("phone", (char)0x260E, true),
                new EntityMapping("puncsp", (char)0x2008, true),
                new EntityMapping("rdquor", (char)0x201D, true),
                new EntityMapping("rect", (char)0x25AD, true),
                new EntityMapping("rsquor", (char)0x2019, true),
                new EntityMapping("rtri", (char)0x25B9, true),
                new EntityMapping("rtrif", (char)0x25B8, true),
                new EntityMapping("rx", (char)0x211E, true),
                new EntityMapping("sext", (char)0x2736, true),
                new EntityMapping("sharp", (char)0x266F, true),
                //duplicated new EntityMapping("spades", (char)0x2660, true),
                new EntityMapping("squ", (char)0x25A1, true),
                new EntityMapping("squf", (char)0x25AA, true),
                new EntityMapping("star", (char)0x2606, true),
                new EntityMapping("starf", (char)0x2605, true),
                new EntityMapping("target", (char)0x2316, true),
                new EntityMapping("telrec", (char)0x2315, true),
                //duplicated new EntityMapping("thinsp", (char)0x2009, true),
                new EntityMapping("uhblk", (char)0x2580, true),
                new EntityMapping("ulcrop", (char)0x230F, true),
                new EntityMapping("urcrop", (char)0x230E, true),
                new EntityMapping("utri", (char)0x25B5, true),
                new EntityMapping("utrif", (char)0x25B4, true),
                new EntityMapping("vellip", (char)0x22EE, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOPUB.ToString();
            return eSet;
        }

        protected override EntitySet CreateISOTECHEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("And", (char)0x2A53, true),
                new EntityMapping("Cconint", (char)0x2230, true),
                new EntityMapping("Conint", (char)0x222F, true),
                new EntityMapping("Dot", (char)0x00A8, true),
                new EntityMapping("DotDot", (char)0x20DC, true),
                new EntityMapping("Int", (char)0x222C, true),
                new EntityMapping("Lang", (char)0x27EA, true),
                new EntityMapping("Not", (char)0x2AEC, true),
                new EntityMapping("Or", (char)0x2A54, true),
                //duplicated new EntityMapping("Prime", (char)0x2033, true),
                new EntityMapping("Rang", (char)0x27EB, true),
                new EntityMapping("Verbar", (char)0x2016, true),
                new EntityMapping("acd", (char)0x223F, true),
                new EntityMapping("aleph", (char)0x2135, true),
                //duplicated new EntityMapping("and", (char)0x2227, true),
                new EntityMapping("andand", (char)0x2A55, true),
                new EntityMapping("andd", (char)0x2A5C, true),
                new EntityMapping("andslope", (char)0x2A58, true),
                new EntityMapping("andv", (char)0x2A5A, true),
                new EntityMapping("angrt", (char)0x221F, true),
                new EntityMapping("angsph", (char)0x2222, true),
                new EntityMapping("angst", (char)0x212B, true),
                new EntityMapping("ap", (char)0x2248, true),
                new EntityMapping("apacir", (char)0x2A6F, true),
                new EntityMapping("awconint", (char)0x2233, true),
                new EntityMapping("awint", (char)0x2A11, true),
                new EntityMapping("bNot", (char)0x2AED, true),
                new EntityMapping("becaus", (char)0x2235, true),
                new EntityMapping("bernou", (char)0x212C, true),
                new EntityMapping("bne", (char)0x003D, false),
                new EntityMapping("bnequiv", (char)0x2261, false),
                new EntityMapping("bnot", (char)0x2310, true),
                new EntityMapping("bottom", (char)0x22A5, true),
                //duplicated new EntityMapping("cap", (char)0x2229, true),
                new EntityMapping("cirfnint", (char)0x2A10, true),
                new EntityMapping("compfn", (char)0x2218, true),
                //duplicated new EntityMapping("cong", (char)0x2245, true),
                new EntityMapping("conint", (char)0x222E, true),
                new EntityMapping("ctdot", (char)0x22EF, true),
                //duplicated new EntityMapping("cup", (char)0x222A, true),
                new EntityMapping("cwconint", (char)0x2232, true),
                new EntityMapping("cwint", (char)0x2231, true),
                new EntityMapping("cylcty", (char)0x232D, true),
                new EntityMapping("disin", (char)0x22F2, true),
                new EntityMapping("dsol", (char)0x29F6, true),
                new EntityMapping("dtdot", (char)0x22F1, true),
                new EntityMapping("dwangle", (char)0x29A6, true),
                new EntityMapping("elinters", (char)0x23E7, true),
                new EntityMapping("epar", (char)0x22D5, true),
                new EntityMapping("eparsl", (char)0x29E3, true),
                //duplicated new EntityMapping("equiv", (char)0x2261, true),
                new EntityMapping("eqvparsl", (char)0x29E5, true),
                //duplicated new EntityMapping("exist", (char)0x2203, true),
                new EntityMapping("fltns", (char)0x25B1, true),
                //duplicated new EntityMapping("fnof", (char)0x0192, true),
                //duplicated new EntityMapping("forall", (char)0x2200, true),
                new EntityMapping("fpartint", (char)0x2A0D, true),
                //duplicated new EntityMapping("ge", (char)0x2265, true),
                new EntityMapping("hamilt", (char)0x210B, true),
                new EntityMapping("iff", (char)0x21D4, true),
                new EntityMapping("iinfin", (char)0x29DC, true),
                new EntityMapping("imped", (char)0x01B5, true),
                //duplicated new EntityMapping("infin", (char)0x221E, true),
                new EntityMapping("infintie", (char)0x29DD, true),
                //duplicated new EntityMapping("int", (char)0x222B, true),
                new EntityMapping("intlarhk", (char)0x2A17, true),
                //duplicated new EntityMapping("isin", (char)0x2208, true),
                new EntityMapping("isinE", (char)0x22F9, true),
                new EntityMapping("isindot", (char)0x22F5, true),
                new EntityMapping("isins", (char)0x22F4, true),
                new EntityMapping("isinsv", (char)0x22F3, true),
                new EntityMapping("isinv", (char)0x2208, true),
                //duplicated new EntityMapping("lArr", (char)0x21D0, true),
                new EntityMapping("lagran", (char)0x2112, true),
                //duplicated new EntityMapping("lang", (char)0x2329, true),
                new EntityMapping("lbbrk", (char)0x2997, true),
                //duplicated new EntityMapping("le", (char)0x2264, true),
                new EntityMapping("loang", (char)0x27EC, true),
                new EntityMapping("lobrk", (char)0x27E6, true),
                new EntityMapping("lopar", (char)0x2985, true),
                //duplicated new EntityMapping("lowast", (char)0x2217, true),
                //duplicated new EntityMapping("minus", (char)0x2212, true),
                new EntityMapping("mnplus", (char)0x2213, true),
                //duplicated new EntityMapping("nabla", (char)0x2207, true),
                //duplicated new EntityMapping("ne", (char)0x2260, true),
                new EntityMapping("nedot", (char)0x2250, false),
                new EntityMapping("nhpar", (char)0x2AF2, true),
                //duplicated new EntityMapping("ni", (char)0x220B, true),
                new EntityMapping("nis", (char)0x22FC, true),
                new EntityMapping("nisd", (char)0x22FA, true),
                new EntityMapping("niv", (char)0x220B, true),
                //duplicated new EntityMapping("notin", (char)0x2209, true),
                new EntityMapping("notinE", (char)0x22F9, false),
                new EntityMapping("notindot", (char)0x22F5, false),
                new EntityMapping("notinva", (char)0x2209, true),
                new EntityMapping("notinvb", (char)0x22F7, true),
                new EntityMapping("notinvc", (char)0x22F6, true),
                new EntityMapping("notni", (char)0x220C, true),
                new EntityMapping("notniva", (char)0x220C, true),
                new EntityMapping("notnivb", (char)0x22FE, true),
                new EntityMapping("notnivc", (char)0x22FD, true),
                new EntityMapping("nparsl", (char)0x2AFD, false),
                new EntityMapping("npart", (char)0x2202, false),
                new EntityMapping("npolint", (char)0x2A14, true),
                new EntityMapping("nvinfin", (char)0x29DE, true),
                new EntityMapping("olcross", (char)0x29BB, true),
                //duplicated new EntityMapping("or", (char)0x2228, true),
                new EntityMapping("ord", (char)0x2A5D, true),
                new EntityMapping("order", (char)0x2134, true),
                new EntityMapping("oror", (char)0x2A56, true),
                new EntityMapping("orslope", (char)0x2A57, true),
                new EntityMapping("orv", (char)0x2A5B, true),
                new EntityMapping("par", (char)0x2225, true),
                new EntityMapping("parsl", (char)0x2AFD, true),
                //duplicated new EntityMapping("part", (char)0x2202, true),
                //duplicated new EntityMapping("permil", (char)0x2030, true),
                //duplicated new EntityMapping("perp", (char)0x22A5, true),
                new EntityMapping("pertenk", (char)0x2031, true),
                new EntityMapping("phmmat", (char)0x2133, true),
                new EntityMapping("pointint", (char)0x2A15, true),
                //duplicated new EntityMapping("prime", (char)0x2032, true),
                new EntityMapping("profalar", (char)0x232E, true),
                new EntityMapping("profline", (char)0x2312, true),
                new EntityMapping("profsurf", (char)0x2313, true),
                //duplicated new EntityMapping("prop", (char)0x221D, true),
                new EntityMapping("qint", (char)0x2A0C, true),
                new EntityMapping("qprime", (char)0x2057, true),
                new EntityMapping("quatint", (char)0x2A16, true),
                //duplicated new EntityMapping("rArr", (char)0x21D2, true),
                //duplicated new EntityMapping("radic", (char)0x221A, true),
                //duplicated new EntityMapping("rang", (char)0x232A, true),
                new EntityMapping("rbbrk", (char)0x2998, true),
                new EntityMapping("roang", (char)0x27ED, true),
                new EntityMapping("robrk", (char)0x27E7, true),
                new EntityMapping("ropar", (char)0x2986, true),
                new EntityMapping("rppolint", (char)0x2A12, true),
                new EntityMapping("scpolint", (char)0x2A13, true),
                //duplicated new EntityMapping("sim", (char)0x223C, true),
                new EntityMapping("simdot", (char)0x2A6A, true),
                new EntityMapping("sime", (char)0x2243, true),
                new EntityMapping("smeparsl", (char)0x29E4, true),
                new EntityMapping("square", (char)0x25A1, true),
                new EntityMapping("squarf", (char)0x25AA, true),
                new EntityMapping("strns", (char)0x00AF, true),
                //duplicated new EntityMapping("sub", (char)0x2282, true),
                //duplicated new EntityMapping("sube", (char)0x2286, true),
                //duplicated new EntityMapping("sup", (char)0x2283, true),
                //duplicated new EntityMapping("supe", (char)0x2287, true),
                new EntityMapping("tdot", (char)0x20DB, true),
                //duplicated new EntityMapping("there4", (char)0x2234, true),
                new EntityMapping("tint", (char)0x222D, true),
                new EntityMapping("top", (char)0x22A4, true),
                new EntityMapping("topbot", (char)0x2336, true),
                new EntityMapping("topcir", (char)0x2AF1, true),
                new EntityMapping("tprime", (char)0x2034, true),
                new EntityMapping("utdot", (char)0x22F0, true),
                new EntityMapping("uwangle", (char)0x29A7, true),
                new EntityMapping("vangrt", (char)0x299C, true),
                new EntityMapping("veeeq", (char)0x225A, true),
                new EntityMapping("wedgeq", (char)0x2259, true),
                new EntityMapping("xnis", (char)0x22FB, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOTECH.ToString();
            return eSet;
        }
        protected override EntitySet CreateISOAMSNEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("gnE", (char)0x2269, true),
                new EntityMapping("gnap", (char)0x2A8A, true),
                new EntityMapping("gne", (char)0x2A88, true),
                new EntityMapping("gnsim", (char)0x22E7, true),
                new EntityMapping("gvnE", (char)0x2269, false),
                new EntityMapping("lnE", (char)0x2268, true),
                new EntityMapping("lnap", (char)0x2A89, true),
                new EntityMapping("lne", (char)0x2A87, true),
                new EntityMapping("lnsim", (char)0x22E6, true),
                new EntityMapping("lvnE", (char)0x2268, false),
                new EntityMapping("nGg", (char)0x22D9, false),
                new EntityMapping("nGt", (char)0x226B, false),
                new EntityMapping("nGtv", (char)0x226B, false),
                new EntityMapping("nLl", (char)0x22D8, false),
                new EntityMapping("nLt", (char)0x226A, false),
                new EntityMapping("nLtv", (char)0x226A, false),
                new EntityMapping("nVDash", (char)0x22AF, true),
                new EntityMapping("nVdash", (char)0x22AE, true),
                new EntityMapping("nap", (char)0x2249, true),
                new EntityMapping("napE", (char)0x2A70, false),
                new EntityMapping("napid", (char)0x224B, false),
                new EntityMapping("ncong", (char)0x2247, true),
                new EntityMapping("ncongdot", (char)0x2A6D, false),
                new EntityMapping("nequiv", (char)0x2262, true),
                new EntityMapping("ngE", (char)0x2267, false),
                new EntityMapping("nge", (char)0x2271, true),
                new EntityMapping("nges", (char)0x2A7E, false),
                new EntityMapping("ngsim", (char)0x2275, true),
                new EntityMapping("ngt", (char)0x226F, true),
                new EntityMapping("nlE", (char)0x2266, false),
                new EntityMapping("nle", (char)0x2270, true),
                new EntityMapping("nles", (char)0x2A7D, false),
                new EntityMapping("nlsim", (char)0x2274, true),
                new EntityMapping("nlt", (char)0x226E, true),
                new EntityMapping("nltri", (char)0x22EA, true),
                new EntityMapping("nltrie", (char)0x22EC, true),
                new EntityMapping("nmid", (char)0x2224, true),
                new EntityMapping("npar", (char)0x2226, true),
                new EntityMapping("npr", (char)0x2280, true),
                new EntityMapping("nprcue", (char)0x22E0, true),
                new EntityMapping("npre", (char)0x2AAF, false),
                new EntityMapping("nrtri", (char)0x22EB, true),
                new EntityMapping("nrtrie", (char)0x22ED, true),
                new EntityMapping("nsc", (char)0x2281, true),
                new EntityMapping("nsccue", (char)0x22E1, true),
                new EntityMapping("nsce", (char)0x2AB0, false),
                new EntityMapping("nsim", (char)0x2241, true),
                new EntityMapping("nsime", (char)0x2244, true),
                new EntityMapping("nsmid", (char)0x2224, true),
                new EntityMapping("nspar", (char)0x2226, true),
                new EntityMapping("nsqsube", (char)0x22E2, true),
                new EntityMapping("nsqsupe", (char)0x22E3, true),
                //duplicated new EntityMapping("nsub", (char)0x2284, true),
                new EntityMapping("nsubE", (char)0x2AC5, false),
                new EntityMapping("nsube", (char)0x2288, true),
                new EntityMapping("nsup", (char)0x2285, true),
                new EntityMapping("nsupE", (char)0x2AC6, false),
                new EntityMapping("nsupe", (char)0x2289, true),
                new EntityMapping("ntgl", (char)0x2279, true),
                new EntityMapping("ntlg", (char)0x2278, true),
                new EntityMapping("nvDash", (char)0x22AD, true),
                new EntityMapping("nvap", (char)0x224D, false),
                new EntityMapping("nvdash", (char)0x22AC, true),
                new EntityMapping("nvge", (char)0x2265, false),
                //duplicated new EntityMapping("nvgt", (char)0x003E),
                new EntityMapping("nvle", (char)0x2264, false),
                //duplicated new EntityMapping("nvlt", (char)0x003C),
                new EntityMapping("nvltrie", (char)0x22B4, false),
                new EntityMapping("nvrtrie", (char)0x22B5, false),
                new EntityMapping("nvsim", (char)0x223C, false),
                new EntityMapping("parsim", (char)0x2AF3, true),
                new EntityMapping("prnE", (char)0x2AB5, true),
                new EntityMapping("prnap", (char)0x2AB9, true),
                new EntityMapping("prnsim", (char)0x22E8, true),
                new EntityMapping("rnmid", (char)0x2AEE, true),
                new EntityMapping("scnE", (char)0x2AB6, true),
                new EntityMapping("scnap", (char)0x2ABA, true),
                new EntityMapping("scnsim", (char)0x22E9, true),
                new EntityMapping("simne", (char)0x2246, true),
                new EntityMapping("solbar", (char)0x233F, true),
                new EntityMapping("subnE", (char)0x2ACB, true),
                new EntityMapping("subne", (char)0x228A, true),
                new EntityMapping("supnE", (char)0x2ACC, true),
                new EntityMapping("supne", (char)0x228B, true),
                new EntityMapping("vnsub", (char)0x2282, false),
                new EntityMapping("vnsup", (char)0x2283, false),
                new EntityMapping("vsubnE", (char)0x2ACB, false),
                new EntityMapping("vsubne", (char)0x228A, false),
                new EntityMapping("vsupnE", (char)0x2ACC, false),
                new EntityMapping("vsupne", (char)0x228B, false)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.ISOAMSN.ToString();
            return eSet;
        }

        protected override EntitySet CreateHTMLSPECIALEntitySet()
        {
            EntityMapping[] mappings = new[]
            {
                new EntityMapping("Dagger",    (char)8225, true),
                new EntityMapping("OElig",    (char)338, true),
                new EntityMapping("Scaron",    (char)352, true),
                new EntityMapping("Yuml",    (char)376, true),
                new EntityMapping("amp",    (char)38, true,true),
                new EntityMapping("bdquo",    (char)8222, true),
                new EntityMapping("circ",    (char)710, true),
                new EntityMapping("dagger",    (char)8224, true),
                new EntityMapping("emsp",    (char)8195, true),
                new EntityMapping("ensp",    (char)8194, true),
                new EntityMapping("gt",    (char)62, true, true),
                new EntityMapping("ldquo",    (char)8220, true),
                new EntityMapping("lrm",    (char)8206, true),
                new EntityMapping("lsaquo",    (char)8249, true),
                new EntityMapping("lsquo",    (char)8216, true),
                new EntityMapping("lt",    (char)60, true, true),
                new EntityMapping("mdash",    (char)8212, true),
                // MM 2008-10-22: explicitly added nbsp to HTML special set to avoid
                // having to map the entire Numeric and Special Graphic set,
                // (which would involve &colon; etc, typically not desirable)
                // for the HTML filter (in TRADOS tools the nbsp was incorrectly
                // part of the Added Latin 1 set, that is no longer the case).
                new EntityMapping("nbsp",    (char)0x00A0, true),
                new EntityMapping("ndash",    (char)8211, true),
                new EntityMapping("oelig",    (char)339, true),
                new EntityMapping("permil",    (char)8240, true),
                new EntityMapping("quot",    (char)34, true, true),
                new EntityMapping("rdquo",    (char)8221, true),
                new EntityMapping("rlm",    (char)8207, true),
                new EntityMapping("rsaquo",    (char)8250, true),
                new EntityMapping("rsquo",    (char)8217, true),
                new EntityMapping("sbquo",    (char)8218, true),
                new EntityMapping("scaron",    (char)353, true),
                new EntityMapping("thinsp",    (char)8201, true),
                new EntityMapping("tilde",    (char)732, true),
                new EntityMapping("zwj",    (char)8205, true),
                new EntityMapping("zwnj",    (char)8204, true)
            };

            EntitySet eSet = new EntitySet(mappings, true);
            eSet.Name = WellKnownEntitySetNames.HTMLSPECIAL.ToString();
            return eSet;
        }
    }
}
