//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multilingual.XML.FileType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multilingual.XML.FileType.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entity.
        /// </summary>
        public static string AddEntityMappingFormTitle {
            get {
                return ResourceManager.GetString("AddEntityMappingFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DefaultPlaceHolders {
            get {
                object obj = ResourceManager.GetObject("DefaultPlaceHolders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Entity Name.
        /// </summary>
        public static string DuplicateEntitiyNameInListTitle {
            get {
                return ResourceManager.GetString("DuplicateEntitiyNameInListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity with the same name already exists. Please choose a unique name..
        /// </summary>
        public static string DuplicateEntityNameInList {
            get {
                return ResourceManager.GetString("DuplicateEntityNameInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Entity.
        /// </summary>
        public static string EditEntityMappingFormTitle {
            get {
                return ResourceManager.GetString("EditEntityMappingFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string EntitySetTypeCustom {
            get {
                return ResourceManager.GetString("EntitySetTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string EntitySetTypeDefault {
            get {
                return ResourceManager.GetString("EntitySetTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect File Type &apos;{0}&apos;, expected: &apos;{1}&apos;.
        /// </summary>
        public static string ExceptionMessage_Incorrect_File_Type {
            get {
                return ResourceManager.GetString("ExceptionMessage_Incorrect_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate multilingual translations from a monolingual file!.
        /// </summary>
        public static string ExceptionMessage_Unable_To_Generate_Multilingual_From_Monolingual_File {
            get {
                return ResourceManager.GetString("ExceptionMessage_Unable_To_Generate_Multilingual_From_Monolingual_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import multilingual translations from a monolingual file!.
        /// </summary>
        public static string ExceptionMessage_Unable_To_Import_From_Monolingual_File {
            get {
                return ResourceManager.GetString("ExceptionMessage_Unable_To_Import_From_Monolingual_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the language {0}. Please check that the language is mapped correctly in the File Type settings of the project..
        /// </summary>
        public static string ExceptionMessage_UnableToLocateTheMappedLanguage_ {
            get {
                return ResourceManager.GetString("ExceptionMessage_UnableToLocateTheMappedLanguage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ForumIcon {
            get {
                object obj = ResourceManager.GetObject("ForumIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string GenericXml_2_NamespaceMapping {
            get {
                return ResourceManager.GetString("GenericXml_2_NamespaceMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace Settings for XML Parser.
        /// </summary>
        public static string GenericXml_2_NamespaceMapping_Description {
            get {
                return ResourceManager.GetString("GenericXml_2_NamespaceMapping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string GenericXml_2_NamespaceMapping_Name {
            get {
                return ResourceManager.GetString("GenericXml_2_NamespaceMapping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new attribute (Ctrl+N).
        /// </summary>
        public static string Header_AddNewCommentProperty {
            get {
                return ResourceManager.GetString("Header_AddNewCommentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new language (Ctrl+N).
        /// </summary>
        public static string Header_AddNewLanguage {
            get {
                return ResourceManager.GetString("Header_AddNewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected attribute (Ctrl+E).
        /// </summary>
        public static string Header_EditSelectedCommentProperty {
            get {
                return ResourceManager.GetString("Header_EditSelectedCommentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected language (Ctrl+E).
        /// </summary>
        public static string Header_EditSelectedLanguage {
            get {
                return ResourceManager.GetString("Header_EditSelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected attributes (Delete).
        /// </summary>
        public static string Header_RemoveSelectedCommentProperties {
            get {
                return ResourceManager.GetString("Header_RemoveSelectedCommentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected languages (Delete).
        /// </summary>
        public static string Header_RemoveSelectedLanguages {
            get {
                return ResourceManager.GetString("Header_RemoveSelectedLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Special.
        /// </summary>
        public static string HTMLSPECIAL {
            get {
                return ResourceManager.GetString("HTMLSPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Symbols.
        /// </summary>
        public static string HTMLSYMBOL {
            get {
                return ResourceManager.GetString("HTMLSYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected placeholder patterns.
        /// </summary>
        public static string InformationMessage_ExortSelectedPlaceholders {
            get {
                return ResourceManager.GetString("InformationMessage_ExortSelectedPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was exported successfully to selected location..
        /// </summary>
        public static string InformationMessage_FileWasExportedSuccessfully {
            get {
                return ResourceManager.GetString("InformationMessage_FileWasExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one placeholder pattern to export..
        /// </summary>
        public static string InformationMessage_PleaseSelectAtLeastOnePlaceholder {
            get {
                return ResourceManager.GetString("InformationMessage_PleaseSelectAtLeastOnePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the files you want to import.
        /// </summary>
        public static string InformationMessage_SelectTheImportFiles {
            get {
                return ResourceManager.GetString("InformationMessage_SelectTheImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Math Symbols: Arrow relations.
        /// </summary>
        public static string ISOAMSA {
            get {
                return ResourceManager.GetString("ISOAMSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Math Symbols: Binary operators.
        /// </summary>
        public static string ISOAMSB {
            get {
                return ResourceManager.GetString("ISOAMSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Math Symbols: Delimiters.
        /// </summary>
        public static string ISOAMSC {
            get {
                return ResourceManager.GetString("ISOAMSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Math Symbols: Operations.
        /// </summary>
        public static string ISOAMSN {
            get {
                return ResourceManager.GetString("ISOAMSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Math Symbols: Ordinary.
        /// </summary>
        public static string ISOAMSO {
            get {
                return ResourceManager.GetString("ISOAMSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Math Symbols: Relations.
        /// </summary>
        public static string ISOAMSR {
            get {
                return ResourceManager.GetString("ISOAMSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box and Line Drawing.
        /// </summary>
        public static string ISOBOX {
            get {
                return ResourceManager.GetString("ISOBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Cyrilic.
        /// </summary>
        public static string ISOCYR1 {
            get {
                return ResourceManager.GetString("ISOCYR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Russian Cyrilic.
        /// </summary>
        public static string ISOCYR2 {
            get {
                return ResourceManager.GetString("ISOCYR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diacritical Marks.
        /// </summary>
        public static string ISODIA {
            get {
                return ResourceManager.GetString("ISODIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek Letters.
        /// </summary>
        public static string ISOGRK1 {
            get {
                return ResourceManager.GetString("ISOGRK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monotoniko Greek.
        /// </summary>
        public static string ISOGRK2 {
            get {
                return ResourceManager.GetString("ISOGRK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek Symbols.
        /// </summary>
        public static string ISOGRK3 {
            get {
                return ResourceManager.GetString("ISOGRK3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Greek Symbols.
        /// </summary>
        public static string ISOGRK4 {
            get {
                return ResourceManager.GetString("ISOGRK4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Latin 1.
        /// </summary>
        public static string ISOLAT1 {
            get {
                return ResourceManager.GetString("ISOLAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Latin 2.
        /// </summary>
        public static string ISOLAT2 {
            get {
                return ResourceManager.GetString("ISOLAT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Fraktur Font.
        /// </summary>
        public static string ISOMFRK {
            get {
                return ResourceManager.GetString("ISOMFRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Open Face Font.
        /// </summary>
        public static string ISOMOPF {
            get {
                return ResourceManager.GetString("ISOMOPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Script Font.
        /// </summary>
        public static string ISOMSCR {
            get {
                return ResourceManager.GetString("ISOMSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric and Special Graphic.
        /// </summary>
        public static string ISONUM {
            get {
                return ResourceManager.GetString("ISONUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing.
        /// </summary>
        public static string ISOPUB {
            get {
                return ResourceManager.GetString("ISOPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Technical.
        /// </summary>
        public static string ISOTECH {
            get {
                return ResourceManager.GetString("ISOTECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon mlXML {
            get {
                object obj = ResourceManager.GetObject("mlXML", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mlXML_image {
            get {
                object obj = ResourceManager.GetObject("mlXML_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string MultilingualXMLFileType_CommentMappingPage_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_CommentMappingPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string MultilingualXMLFileType_CommentMappingPage_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_CommentMappingPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilingual XML File Type Component Builder.
        /// </summary>
        public static string MultilingualXMLFileType_ComponentBuilder_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_ComponentBuilder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilingual XML File Type Component Builder.
        /// </summary>
        public static string MultilingualXMLFileType_ComponentBuilder_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_ComponentBuilder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Content.
        /// </summary>
        public static string MultilingualXMLFileType_EmbeddedContentPage_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_EmbeddedContentPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Content.
        /// </summary>
        public static string MultilingualXMLFileType_EmbeddedContentPage_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_EmbeddedContentPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        public static string MultilingualXMLFileType_EntitiesPage_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_EntitiesPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        public static string MultilingualXMLFileType_EntitiesPage_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_EntitiesPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Multilingual Translations (XML).
        /// </summary>
        public static string MultilingualXMLFileType_ExportBatchTask_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_ExportBatchTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Multilingual Translations (XML).
        /// </summary>
        public static string MultilingualXMLFileType_ExportBatchTask_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_ExportBatchTask_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Multilingual Translations (XML).
        /// </summary>
        public static string MultilingualXMLFileType_ImportBatchTask_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_ImportBatchTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Multilingual Translations (XML).
        /// </summary>
        public static string MultilingualXMLFileType_ImportBatchTask_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_ImportBatchTask_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify languages for the Multilingual XML.
        /// </summary>
        public static string MultilingualXMLFileType_LanguageMappingPage_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_LanguageMappingPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Mapping.
        /// </summary>
        public static string MultilingualXMLFileType_LanguageMappingPage_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_LanguageMappingPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholders.
        /// </summary>
        public static string MultilingualXMLFileType_PlaceholdersPage_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_PlaceholdersPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholders.
        /// </summary>
        public static string MultilingualXMLFileType_PlaceholdersPage_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_PlaceholdersPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string MultilingualXMLFileType_WriterPage_Description {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_WriterPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string MultilingualXMLFileType_WriterPage_Name {
            get {
                return ResourceManager.GetString("MultilingualXMLFileType_WriterPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilingual XML File Type.
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilingual XML File Type.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Filter Settings.
        /// </summary>
        public static string Plugin_Name1 {
            get {
                return ResourceManager.GetString("Plugin_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to reset all entities in this set to default values?.
        /// </summary>
        public static string ResetEntitySet {
            get {
                return ResourceManager.GetString("ResetEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Entity Set to Defaults.
        /// </summary>
        public static string ResetEntitySetTitle {
            get {
                return ResourceManager.GetString("ResetEntitySetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0} from the AppStore.
        /// </summary>
        public static string TellMe_Download_Plugin_From_AppStore {
            get {
                return ResourceManager.GetString("TellMe_Download_Plugin_From_AppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results.
        /// </summary>
        public static string TellMe_String_Results {
            get {
                return ResourceManager.GetString("TellMe_String_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TellMe provider.
        /// </summary>
        public static string TellMe_String_TellMe_Provider {
            get {
                return ResourceManager.GetString("TellMe_String_TellMe_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute XPath query that locates the languages root element (e.g. /root/trans-unit).
        /// </summary>
        public static string ToolTip_AbsoluteXPathQueryLanguagesRoot {
            get {
                return ResourceManager.GetString("ToolTip_AbsoluteXPathQueryLanguagesRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the comment element, typically called &apos;Comment&apos;, &apos;Note&apos; etc....
        /// </summary>
        public static string ToolTip_CommentElementName {
            get {
                return ResourceManager.GetString("ToolTip_CommentElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression that recognizes text which should be converted to a placeable tag..
        /// </summary>
        public static string ToolTip_PlaceholderPatternExpression {
            get {
                return ResourceManager.GetString("ToolTip_PlaceholderPatternExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder patterns are regular expressions that recognize text which should be converted to placeholder tags..
        /// </summary>
        public static string ToolTip_PlaceholderPatterns {
            get {
                return ResourceManager.GetString("ToolTip_PlaceholderPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative XPath query that locates the comments root element..
        /// </summary>
        public static string ToolTip_RelativeXPathQueryCommentsRoot {
            get {
                return ResourceManager.GetString("ToolTip_RelativeXPathQueryCommentsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative XPath query that locates the language element containing the segment content..
        /// </summary>
        public static string ToolTip_RelativeXPathQueryLanguagesRoot {
            get {
                return ResourceManager.GetString("ToolTip_RelativeXPathQueryLanguagesRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Entity Set.
        /// </summary>
        public static string UnknownEntitySet {
            get {
                return ResourceManager.GetString("UnknownEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        public static string UserDefinedEntitySetName {
            get {
                return ResourceManager.GetString("UserDefinedEntitySetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute.
        /// </summary>
        public static string WindowTitle_Add_CommentProperty {
            get {
                return ResourceManager.GetString("WindowTitle_Add_CommentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language.
        /// </summary>
        public static string WindowTitle_Add_Language {
            get {
                return ResourceManager.GetString("WindowTitle_Add_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Placeholder Pattern.
        /// </summary>
        public static string WindowTitle_Add_PlaceholderPattern {
            get {
                return ResourceManager.GetString("WindowTitle_Add_PlaceholderPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attribute.
        /// </summary>
        public static string WindowTitle_Edit_CommentProperty {
            get {
                return ResourceManager.GetString("WindowTitle_Edit_CommentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Language.
        /// </summary>
        public static string WindowTitle_Edit_Language {
            get {
                return ResourceManager.GetString("WindowTitle_Edit_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Placeholder Pattern.
        /// </summary>
        public static string WindowTitle_Edit_PlaceholderPattern {
            get {
                return ResourceManager.GetString("WindowTitle_Edit_PlaceholderPattern", resourceCulture);
            }
        }
    }
}
