//-----------------------------------------------------------------------
// <copyright file="PluginProperties.cs" company="SDL plc">
//  Copyright (c) SDL plc. All rights reserved.
// </copyright>
// <autogenerated from="languageplatform"/>
//-----------------------------------------------------------------------

using Sdl.Core.PluginFramework;

// TODO: edit the Plugin_Name string in  PluginResources.resx to change the name of your plug-in
[assembly: Plugin("Plugin_Name")]
