//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomViewExample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomViewExample.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} useful tips..
        /// </summary>
        internal static string Added__0__useful_tips {
            get {
                return ResourceManager.GetString("Added__0__useful_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string CustomViewExample_ActionsGroup_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_ActionsGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Useful Tips.
        /// </summary>
        internal static string CustomViewExample_AddUsefulTipsAction_Description {
            get {
                return ResourceManager.GetString("CustomViewExample_AddUsefulTipsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CustomViewExample_AddUsefulTipsAction_Icon {
            get {
                object obj = ResourceManager.GetObject("CustomViewExample_AddUsefulTipsAction_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Useful Tips.
        /// </summary>
        internal static string CustomViewExample_AddUsefulTipsAction_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_AddUsefulTipsAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string CustomViewExample_ConfigurationGroup_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_ConfigurationGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom View Example Description.
        /// </summary>
        internal static string CustomViewExample_Description {
            get {
                return ResourceManager.GetString("CustomViewExample_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string CustomViewExample_EditorActionsGroup_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_EditorActionsGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CustomViewExample_Icon {
            get {
                object obj = ResourceManager.GetObject("CustomViewExample_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom View Example.
        /// </summary>
        internal static string CustomViewExample_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CustomViewExample_OpenSettingsAction_Description {
            get {
                return ResourceManager.GetString("CustomViewExample_OpenSettingsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CustomViewExample_OpenSettingsAction_Icon {
            get {
                object obj = ResourceManager.GetObject("CustomViewExample_OpenSettingsAction_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CustomViewExample_OpenSettingsAction_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_OpenSettingsAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Useful Tips.
        /// </summary>
        internal static string CustomViewExample_RemoveUsefulTipsAction_Description {
            get {
                return ResourceManager.GetString("CustomViewExample_RemoveUsefulTipsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CustomViewExample_RemoveUsefulTipsAction_Icon {
            get {
                object obj = ResourceManager.GetObject("CustomViewExample_RemoveUsefulTipsAction_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Useful Tips.
        /// </summary>
        internal static string CustomViewExample_RemoveUsefulTipsAction_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_RemoveUsefulTipsAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test to confirm the 3rd segment from an embedded document is selected..
        /// </summary>
        internal static string CustomViewExample_SelectSegmentAction_Description {
            get {
                return ResourceManager.GetString("CustomViewExample_SelectSegmentAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 3rd Segment.
        /// </summary>
        internal static string CustomViewExample_SelectSegmentAction_Name {
            get {
                return ResourceManager.GetString("CustomViewExample_SelectSegmentAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;new&apos; useful tips installed!.
        /// </summary>
        internal static string No_new_useful_tips_installed {
            get {
                return ResourceManager.GetString("No_new_useful_tips_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No useful tips found!.
        /// </summary>
        internal static string No_useful_tips_found {
            get {
                return ResourceManager.GetString("No_useful_tips_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No useful tips removed..
        /// </summary>
        internal static string No_useful_tips_removed {
            get {
                return ResourceManager.GetString("No_useful_tips_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom View Example.
        /// </summary>
        internal static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} useful tips..
        /// </summary>
        internal static string Removed__0__useful_tips {
            get {
                return ResourceManager.GetString("Removed__0__useful_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to restart Trados Studio before you changes are applied..
        /// </summary>
        internal static string Restart_Trados_Studio_before_changes_are_applied {
            get {
                return ResourceManager.GetString("Restart_Trados_Studio_before_changes_are_applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Trados Studio to apply changes..
        /// </summary>
        internal static string Restart_Trados_Studio_to_apply_changes {
            get {
                return ResourceManager.GetString("Restart_Trados_Studio_to_apply_changes", resourceCulture);
            }
        }
    }
}
