//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftTranslatorProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftTranslatorProvider.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect without an API key..
        /// </summary>
        public static string ApiKeyError {
            get {
                return ResourceManager.GetString("ApiKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicrosoftTranslatorProvider.
        /// </summary>
        public static string AppLogFolder {
            get {
                return ResourceManager.GetString("AppLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Provider.
        /// </summary>
        public static string BackBtnText {
            get {
                return ResourceManager.GetString("BackBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backImg {
            get {
                object obj = ResourceManager.GetObject("backImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseBtn {
            get {
                return ResourceManager.GetString("BrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CategoryID.
        /// </summary>
        public static string CatIdDescription {
            get {
                return ResourceManager.GetString("CatIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryID is empty.
        /// </summary>
        public static string CatIdError {
            get {
                return ResourceManager.GetString("CatIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings error.
        /// </summary>
        public static string EditSettingsErrorCaption {
            get {
                return ResourceManager.GetString("EditSettingsErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with edit settings:.
        /// </summary>
        public static string EditSettingsGenericErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation..
        /// </summary>
        public static string EditSettingsXmlErrorMessage {
            get {
                return ResourceManager.GetString("EditSettingsXmlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local path to json file cannot be empty..
        /// </summary>
        public static string EmptyJsonFilePathMsg {
            get {
                return ResourceManager.GetString("EmptyJsonFilePathMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty..
        /// </summary>
        public static string EmptyProjectNameMsd {
            get {
                return ResourceManager.GetString("EmptyProjectNameMsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ForumIcon {
            get {
                object obj = ResourceManager.GetObject("ForumIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name..
        /// </summary>
        public static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem checking language pair support..
        /// </summary>
        public static string LangPairAuthErrorMsg1 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that you have entered the correct API key..
        /// </summary>
        public static string LangPairAuthErrorMsg2 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, close/reopen the current dialog and try again.
        /// </summary>
        public static string LangPairAuthErrorMsg3 {
            get {
                return ResourceManager.GetString("LangPairAuthErrorMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicrosoftTranslatorProviderLogs.txt.
        /// </summary>
        public static string LogsFileName {
            get {
                return ResourceManager.GetString("LogsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trados AppStore.
        /// </summary>
        public static string LogsFolderPath {
            get {
                return ResourceManager.GetString("LogsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File error.
        /// </summary>
        public static string lookupFileStructureCheckErrorCaption {
            get {
                return ResourceManager.GetString("lookupFileStructureCheckErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the selected file:.
        /// </summary>
        public static string lookupFileStructureCheckGenericErrorMessage {
            get {
                return ResourceManager.GetString("lookupFileStructureCheckGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Microsoft_Description {
            get {
                return ResourceManager.GetString("Microsoft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap microsoft_image {
            get {
                object obj = ResourceManager.GetObject("microsoft_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Microsoft_Name {
            get {
                return ResourceManager.GetString("Microsoft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Microsoft_NiceName {
            get {
                return ResourceManager.GetString("Microsoft_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Microsoft_Tooltip {
            get {
                return ResourceManager.GetString("Microsoft_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider API Key.
        /// </summary>
        public static string MicrosoftApiDescription {
            get {
                return ResourceManager.GetString("MicrosoftApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Microsoft Translation Provider.
        /// </summary>
        public static string MicrosoftTranslatorProviderPlugin_WinFormsUI {
            get {
                return ResourceManager.GetString("MicrosoftTranslatorProviderPlugin_WinFormsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error: bad credentials.
        /// </summary>
        public static string MsApiBadCredentialsMessage {
            get {
                return ResourceManager.GetString("MsApiBadCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category ID. Use a valid category ID or disable category ID in settings..
        /// </summary>
        public static string MsApiCategoryIdErrorMessage {
            get {
                return ResourceManager.GetString("MsApiCategoryIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get languages for translation.
        /// </summary>
        public static string MsApiFailedGetLanguagesMessage {
            get {
                return ResourceManager.GetString("MsApiFailedGetLanguagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to translate.
        /// </summary>
        public static string MsApiFailedToTranslateMessage {
            get {
                return ResourceManager.GetString("MsApiFailedToTranslateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string MSSubscriptionRegionLabel {
            get {
                return ResourceManager.GetString("MSSubscriptionRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon mstp_icon {
            get {
                object obj = ResourceManager.GetObject("mstp_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter is used to get translations from a customized system built with custom translator.
        ///
        ///Add the Category ID from your Custom Translator project details to this parameter to use your deployed customized system. If you didn&apos;t created such thing, leave it empty..
        /// </summary>
        public static string MSTPCategoryTooltip {
            get {
                return ResourceManager.GetString("MSTPCategoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region you select is the only region that you can use for text translation.
        ///
        ///It must be the same region you selected when you signed up for your multi-service subscription through the Azure portal..
        /// </summary>
        public static string MSTPRegionTooltip {
            get {
                return ResourceManager.GetString("MSTPRegionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember key.
        /// </summary>
        public static string PersistMicrosoft {
            get {
                return ResourceManager.GetString("PersistMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider Trados Plugin.
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Plugin_NiceName {
            get {
                return ResourceManager.GetString("Plugin_NiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator Provider.
        /// </summary>
        public static string Plugin_Tooltip {
            get {
                return ResourceManager.GetString("Plugin_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginsView.
        /// </summary>
        public static string PluginsView {
            get {
                return ResourceManager.GetString("PluginsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostLookup.
        /// </summary>
        public static string PostLookupBrowse {
            get {
                return ResourceManager.GetString("PostLookupBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do post-lookup find/replace.
        /// </summary>
        public static string PostLookupDescription {
            get {
                return ResourceManager.GetString("PostLookupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-lookup filepath cannot be empty. Please add a valid path otherwise uncheck &quot;Do post-lookup checkbox&quot;..
        /// </summary>
        public static string PostLookupEmptyMessage {
            get {
                return ResourceManager.GetString("PostLookupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do post-lookup find/replace filename:.
        /// </summary>
        public static string PostLookupFileName {
            get {
                return ResourceManager.GetString("PostLookupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse or type the location of the post-lookup file.
        /// </summary>
        public static string PostLookupWaterMark {
            get {
                return ResourceManager.GetString("PostLookupWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-lookup file could not be found at the specified path..
        /// </summary>
        public static string PostLookupWrongPathMessage {
            get {
                return ResourceManager.GetString("PostLookupWrongPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreLookup.
        /// </summary>
        public static string PreLookBrowse {
            get {
                return ResourceManager.GetString("PreLookBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pre-lookup find/replace.
        /// </summary>
        public static string PreLookDescription {
            get {
                return ResourceManager.GetString("PreLookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pre-lookup find/replace name:.
        /// </summary>
        public static string PreLookFileName {
            get {
                return ResourceManager.GetString("PreLookFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-lookup filepath cannot be empty. Please add a valid path otherwise uncheck &quot;Do pre-lookup checkbox&quot;..
        /// </summary>
        public static string PreLookupEmptyMessage {
            get {
                return ResourceManager.GetString("PreLookupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse or type the location of the pre-lookup file.
        /// </summary>
        public static string PreLookupWaterMark {
            get {
                return ResourceManager.GetString("PreLookupWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-lookup file could not be found at the specified path..
        /// </summary>
        public static string PreLookupWrongPathMessage {
            get {
                return ResourceManager.GetString("PreLookupWrongPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project location value is required.
        /// </summary>
        public static string ProjectLocationValidation {
            get {
                return ResourceManager.GetString("ProjectLocationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for Microsoft Translator....
        /// </summary>
        public static string PromptForCredentialsCaption_Microsoft {
            get {
                return ResourceManager.GetString("PromptForCredentialsCaption_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string ProviderControl_CategoryFieldName {
            get {
                return ResourceManager.GetString("ProviderControl_CategoryFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about categories .
        /// </summary>
        public static string ProviderControl_CategoryLearnMore {
            get {
                return ResourceManager.GetString("ProviderControl_CategoryLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this option if you want to use the cateogory ID for your Custom Translator..
        /// </summary>
        public static string ProviderControl_CategoryToolTip {
            get {
                return ResourceManager.GetString("ProviderControl_CategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string ProviderControl_RegionFieldName {
            get {
                return ResourceManager.GetString("ProviderControl_RegionFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about regions .
        /// </summary>
        public static string ProviderControl_RegionLearnMore {
            get {
                return ResourceManager.GetString("ProviderControl_RegionLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the region that corresponds to your Azure account..
        /// </summary>
        public static string ProviderControl_RegionToolTip {
            get {
                return ResourceManager.GetString("ProviderControl_RegionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send draft and translated segments.
        /// </summary>
        public static string ReSendDescription {
            get {
                return ResourceManager.GetString("ReSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude tags in translations.
        /// </summary>
        public static string SendPlainDescription {
            get {
                return ResourceManager.GetString("SendPlainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Setting {
            get {
                object obj = ResourceManager.GetObject("Setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find an instance of Microsoft Translator Provider for the current project selected. To add it to your project, follow these steps:
        ///
        ///    1. Open Project Settings
        ///    2. Go to Translation Memory and Automated Translation
        ///    3. Select Use
        ///    4. Via the dropdown menu locate Microsoft Translator Provider.
        /// </summary>
        public static string SettingsAction_NoProviderAvailable {
            get {
                return ResourceManager.GetString("SettingsAction_NoProviderAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsView.
        /// </summary>
        public static string SettingsView {
            get {
                return ResourceManager.GetString("SettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider options.
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TellMe_CommunityForum {
            get {
                object obj = ResourceManager.GetObject("TellMe_CommunityForum", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TellMe_Documentation {
            get {
                object obj = ResourceManager.GetObject("TellMe_Documentation", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TellMe_Settings {
            get {
                object obj = ResourceManager.GetObject("TellMe_Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TellMe_SourceCode {
            get {
                object obj = ResourceManager.GetObject("TellMe_SourceCode", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TellMe_ThirdParty {
            get {
                object obj = ResourceManager.GetObject("TellMe_ThirdParty", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [segment already translated...source not re-sent].
        /// </summary>
        public static string TranslationLookupDraftNotResentMessage {
            get {
                return ResourceManager.GetString("TranslationLookupDraftNotResentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidirectional glossaries.
        /// </summary>
        public static string UnidirectionalGlossary {
            get {
                return ResourceManager.GetString("UnidirectionalGlossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation provider URI not supported..
        /// </summary>
        public static string UriNotSupportedMessage {
            get {
                return ResourceManager.GetString("UriNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose which provider you want to use:.
        /// </summary>
        public static string WindowDescription {
            get {
                return ResourceManager.GetString("WindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WindowsControl_Close {
            get {
                return ResourceManager.GetString("WindowsControl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json file could not be found at the specified path..
        /// </summary>
        public static string WrongJsonFilePath {
            get {
                return ResourceManager.GetString("WrongJsonFilePath", resourceCulture);
            }
        }
    }
}
