//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.MTEdge.Provider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MTEdgeLanguages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MTEdgeLanguages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.MTEdge.Provider.MTEdgeLanguages", typeof(MTEdgeLanguages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string aar {
            get {
                return ResourceManager.GetString("aar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ab.
        /// </summary>
        public static string abk {
            get {
                return ResourceManager.GetString("abk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af.
        /// </summary>
        public static string afr {
            get {
                return ResourceManager.GetString("afr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ak.
        /// </summary>
        public static string aka {
            get {
                return ResourceManager.GetString("aka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sq.
        /// </summary>
        public static string alb {
            get {
                return ResourceManager.GetString("alb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to am.
        /// </summary>
        public static string amh {
            get {
                return ResourceManager.GetString("amh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string ara {
            get {
                return ResourceManager.GetString("ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an.
        /// </summary>
        public static string arg {
            get {
                return ResourceManager.GetString("arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hy.
        /// </summary>
        public static string arm {
            get {
                return ResourceManager.GetString("arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar-arabizi.
        /// </summary>
        public static string arz {
            get {
                return ResourceManager.GetString("arz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string asm {
            get {
                return ResourceManager.GetString("asm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to av.
        /// </summary>
        public static string ava {
            get {
                return ResourceManager.GetString("ava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ae.
        /// </summary>
        public static string ave {
            get {
                return ResourceManager.GetString("ave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ay.
        /// </summary>
        public static string aym {
            get {
                return ResourceManager.GetString("aym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az.
        /// </summary>
        public static string aze {
            get {
                return ResourceManager.GetString("aze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba.
        /// </summary>
        public static string bak {
            get {
                return ResourceManager.GetString("bak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bm.
        /// </summary>
        public static string bam {
            get {
                return ResourceManager.GetString("bam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eu.
        /// </summary>
        public static string baq {
            get {
                return ResourceManager.GetString("baq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be.
        /// </summary>
        public static string bel {
            get {
                return ResourceManager.GetString("bel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bn.
        /// </summary>
        public static string ben {
            get {
                return ResourceManager.GetString("ben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bh.
        /// </summary>
        public static string bih {
            get {
                return ResourceManager.GetString("bih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bi.
        /// </summary>
        public static string bis {
            get {
                return ResourceManager.GetString("bis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.
        /// </summary>
        public static string bos {
            get {
                return ResourceManager.GetString("bos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to br.
        /// </summary>
        public static string bre {
            get {
                return ResourceManager.GetString("bre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bg.
        /// </summary>
        public static string bul {
            get {
                return ResourceManager.GetString("bul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my.
        /// </summary>
        public static string bur {
            get {
                return ResourceManager.GetString("bur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca.
        /// </summary>
        public static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceb.
        /// </summary>
        public static string ceb {
            get {
                return ResourceManager.GetString("ceb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch.
        /// </summary>
        public static string cha {
            get {
                return ResourceManager.GetString("cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ce.
        /// </summary>
        public static string che {
            get {
                return ResourceManager.GetString("che", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-Hans.
        /// </summary>
        public static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh.
        /// </summary>
        public static string chn {
            get {
                return ResourceManager.GetString("chn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chr.
        /// </summary>
        public static string chr {
            get {
                return ResourceManager.GetString("chr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-Hant.
        /// </summary>
        public static string cht {
            get {
                return ResourceManager.GetString("cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cu.
        /// </summary>
        public static string chu {
            get {
                return ResourceManager.GetString("chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cv.
        /// </summary>
        public static string chv {
            get {
                return ResourceManager.GetString("chv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw.
        /// </summary>
        public static string cor {
            get {
                return ResourceManager.GetString("cor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co.
        /// </summary>
        public static string cos {
            get {
                return ResourceManager.GetString("cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cr.
        /// </summary>
        public static string cre {
            get {
                return ResourceManager.GetString("cre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs.
        /// </summary>
        public static string cze {
            get {
                return ResourceManager.GetString("cze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        public static string dan {
            get {
                return ResourceManager.GetString("dan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dv.
        /// </summary>
        public static string div {
            get {
                return ResourceManager.GetString("div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nl.
        /// </summary>
        public static string dut {
            get {
                return ResourceManager.GetString("dut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dz.
        /// </summary>
        public static string dzo {
            get {
                return ResourceManager.GetString("dzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ena {
            get {
                return ResourceManager.GetString("ena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB.
        /// </summary>
        public static string ene {
            get {
                return ResourceManager.GetString("ene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eo.
        /// </summary>
        public static string epo {
            get {
                return ResourceManager.GetString("epo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-AR.
        /// </summary>
        public static string esa {
            get {
                return ResourceManager.GetString("esa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-419.
        /// </summary>
        public static string esl {
            get {
                return ResourceManager.GetString("esl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-MX.
        /// </summary>
        public static string esm {
            get {
                return ResourceManager.GetString("esm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-ES.
        /// </summary>
        public static string ess {
            get {
                return ResourceManager.GetString("ess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        public static string est {
            get {
                return ResourceManager.GetString("est", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ee.
        /// </summary>
        public static string ewe {
            get {
                return ResourceManager.GetString("ewe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prs-AF.
        /// </summary>
        public static string fad {
            get {
                return ResourceManager.GetString("fad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fo.
        /// </summary>
        public static string fao {
            get {
                return ResourceManager.GetString("fao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fj.
        /// </summary>
        public static string fij {
            get {
                return ResourceManager.GetString("fij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fi.
        /// </summary>
        public static string fin {
            get {
                return ResourceManager.GetString("fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string fra {
            get {
                return ResourceManager.GetString("fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-CA.
        /// </summary>
        public static string frc {
            get {
                return ResourceManager.GetString("frc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-FR.
        /// </summary>
        public static string frf {
            get {
                return ResourceManager.GetString("frf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fy.
        /// </summary>
        public static string fry {
            get {
                return ResourceManager.GetString("fry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ff.
        /// </summary>
        public static string ful {
            get {
                return ResourceManager.GetString("ful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka.
        /// </summary>
        public static string geo {
            get {
                return ResourceManager.GetString("geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gd.
        /// </summary>
        public static string gla {
            get {
                return ResourceManager.GetString("gla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ga.
        /// </summary>
        public static string gle {
            get {
                return ResourceManager.GetString("gle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gl.
        /// </summary>
        public static string glg {
            get {
                return ResourceManager.GetString("glg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gv.
        /// </summary>
        public static string glv {
            get {
                return ResourceManager.GetString("glv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el.
        /// </summary>
        public static string gre {
            get {
                return ResourceManager.GetString("gre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gn.
        /// </summary>
        public static string grn {
            get {
                return ResourceManager.GetString("grn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gu.
        /// </summary>
        public static string guj {
            get {
                return ResourceManager.GetString("guj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ht.
        /// </summary>
        public static string hat {
            get {
                return ResourceManager.GetString("hat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        public static string hau {
            get {
                return ResourceManager.GetString("hau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iw.
        /// </summary>
        public static string heb {
            get {
                return ResourceManager.GetString("heb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hz.
        /// </summary>
        public static string her {
            get {
                return ResourceManager.GetString("her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        public static string hin {
            get {
                return ResourceManager.GetString("hin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hmn.
        /// </summary>
        public static string hmn {
            get {
                return ResourceManager.GetString("hmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ho.
        /// </summary>
        public static string hmo {
            get {
                return ResourceManager.GetString("hmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string hrv {
            get {
                return ResourceManager.GetString("hrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hu.
        /// </summary>
        public static string hun {
            get {
                return ResourceManager.GetString("hun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ig.
        /// </summary>
        public static string ibo {
            get {
                return ResourceManager.GetString("ibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string ice {
            get {
                return ResourceManager.GetString("ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to io.
        /// </summary>
        public static string ido {
            get {
                return ResourceManager.GetString("ido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ii.
        /// </summary>
        public static string iii {
            get {
                return ResourceManager.GetString("iii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iu.
        /// </summary>
        public static string iku {
            get {
                return ResourceManager.GetString("iku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ie.
        /// </summary>
        public static string ile {
            get {
                return ResourceManager.GetString("ile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ia.
        /// </summary>
        public static string ina {
            get {
                return ResourceManager.GetString("ina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string ind {
            get {
                return ResourceManager.GetString("ind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ik.
        /// </summary>
        public static string ipk {
            get {
                return ResourceManager.GetString("ipk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it.
        /// </summary>
        public static string ita {
            get {
                return ResourceManager.GetString("ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jv.
        /// </summary>
        public static string jav {
            get {
                return ResourceManager.GetString("jav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        public static string jpn {
            get {
                return ResourceManager.GetString("jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kl.
        /// </summary>
        public static string kal {
            get {
                return ResourceManager.GetString("kal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kn.
        /// </summary>
        public static string kan {
            get {
                return ResourceManager.GetString("kan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ks.
        /// </summary>
        public static string kas {
            get {
                return ResourceManager.GetString("kas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        public static string kau {
            get {
                return ResourceManager.GetString("kau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kk.
        /// </summary>
        public static string kaz {
            get {
                return ResourceManager.GetString("kaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string khm {
            get {
                return ResourceManager.GetString("khm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ki.
        /// </summary>
        public static string kik {
            get {
                return ResourceManager.GetString("kik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rw.
        /// </summary>
        public static string kin {
            get {
                return ResourceManager.GetString("kin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ky.
        /// </summary>
        public static string kir {
            get {
                return ResourceManager.GetString("kir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kv.
        /// </summary>
        public static string kom {
            get {
                return ResourceManager.GetString("kom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string kon {
            get {
                return ResourceManager.GetString("kon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.
        /// </summary>
        public static string kor {
            get {
                return ResourceManager.GetString("kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kj.
        /// </summary>
        public static string kua {
            get {
                return ResourceManager.GetString("kua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ku.
        /// </summary>
        public static string kur {
            get {
                return ResourceManager.GetString("kur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lo.
        /// </summary>
        public static string lao {
            get {
                return ResourceManager.GetString("lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la.
        /// </summary>
        public static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lv.
        /// </summary>
        public static string lav {
            get {
                return ResourceManager.GetString("lav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lif.
        /// </summary>
        public static string lif {
            get {
                return ResourceManager.GetString("lif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li.
        /// </summary>
        public static string lim {
            get {
                return ResourceManager.GetString("lim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        public static string lin {
            get {
                return ResourceManager.GetString("lin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lt.
        /// </summary>
        public static string lit {
            get {
                return ResourceManager.GetString("lit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        public static string ltz {
            get {
                return ResourceManager.GetString("ltz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lu.
        /// </summary>
        public static string lub {
            get {
                return ResourceManager.GetString("lub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lg.
        /// </summary>
        public static string lug {
            get {
                return ResourceManager.GetString("lug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mk.
        /// </summary>
        public static string mac {
            get {
                return ResourceManager.GetString("mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh.
        /// </summary>
        public static string mah {
            get {
                return ResourceManager.GetString("mah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string mal {
            get {
                return ResourceManager.GetString("mal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr.
        /// </summary>
        public static string mar {
            get {
                return ResourceManager.GetString("mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string mlg {
            get {
                return ResourceManager.GetString("mlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt.
        /// </summary>
        public static string mlt {
            get {
                return ResourceManager.GetString("mlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr-ME.
        /// </summary>
        public static string mnt {
            get {
                return ResourceManager.GetString("mnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mn.
        /// </summary>
        public static string mon {
            get {
                return ResourceManager.GetString("mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string mri {
            get {
                return ResourceManager.GetString("mri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to na.
        /// </summary>
        public static string nau {
            get {
                return ResourceManager.GetString("nau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nv.
        /// </summary>
        public static string nav {
            get {
                return ResourceManager.GetString("nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr.
        /// </summary>
        public static string nbl {
            get {
                return ResourceManager.GetString("nbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd.
        /// </summary>
        public static string nde {
            get {
                return ResourceManager.GetString("nde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ng.
        /// </summary>
        public static string ndo {
            get {
                return ResourceManager.GetString("ndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne.
        /// </summary>
        public static string nep {
            get {
                return ResourceManager.GetString("nep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nn.
        /// </summary>
        public static string nno {
            get {
                return ResourceManager.GetString("nno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nb.
        /// </summary>
        public static string nob {
            get {
                return ResourceManager.GetString("nob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string nor {
            get {
                return ResourceManager.GetString("nor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ny.
        /// </summary>
        public static string nya {
            get {
                return ResourceManager.GetString("nya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oc.
        /// </summary>
        public static string oci {
            get {
                return ResourceManager.GetString("oci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oj.
        /// </summary>
        public static string oji {
            get {
                return ResourceManager.GetString("oji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string ori {
            get {
                return ResourceManager.GetString("ori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to om.
        /// </summary>
        public static string orm {
            get {
                return ResourceManager.GetString("orm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to os.
        /// </summary>
        public static string oss {
            get {
                return ResourceManager.GetString("oss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pa.
        /// </summary>
        public static string pan {
            get {
                return ResourceManager.GetString("pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        public static string per {
            get {
                return ResourceManager.GetString("per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pi.
        /// </summary>
        public static string pli {
            get {
                return ResourceManager.GetString("pli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string pol {
            get {
                return ResourceManager.GetString("pol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        public static string por {
            get {
                return ResourceManager.GetString("por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt-BR.
        /// </summary>
        public static string ptb {
            get {
                return ResourceManager.GetString("ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt-PT.
        /// </summary>
        public static string ptp {
            get {
                return ResourceManager.GetString("ptp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ps.
        /// </summary>
        public static string pus {
            get {
                return ResourceManager.GetString("pus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qu.
        /// </summary>
        public static string que {
            get {
                return ResourceManager.GetString("que", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rm.
        /// </summary>
        public static string roh {
            get {
                return ResourceManager.GetString("roh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro.
        /// </summary>
        public static string rum {
            get {
                return ResourceManager.GetString("rum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rn.
        /// </summary>
        public static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sg.
        /// </summary>
        public static string sag {
            get {
                return ResourceManager.GetString("sag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        public static string san {
            get {
                return ResourceManager.GetString("san", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to si.
        /// </summary>
        public static string sin {
            get {
                return ResourceManager.GetString("sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk.
        /// </summary>
        public static string slo {
            get {
                return ResourceManager.GetString("slo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sl.
        /// </summary>
        public static string slv {
            get {
                return ResourceManager.GetString("slv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se.
        /// </summary>
        public static string sme {
            get {
                return ResourceManager.GetString("sme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sm.
        /// </summary>
        public static string smo {
            get {
                return ResourceManager.GetString("smo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn.
        /// </summary>
        public static string sna {
            get {
                return ResourceManager.GetString("sna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sd.
        /// </summary>
        public static string snd {
            get {
                return ResourceManager.GetString("snd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so.
        /// </summary>
        public static string som {
            get {
                return ResourceManager.GetString("som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        public static string sot {
            get {
                return ResourceManager.GetString("sot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        public static string src {
            get {
                return ResourceManager.GetString("src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sc.
        /// </summary>
        public static string srd {
            get {
                return ResourceManager.GetString("srd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        public static string srl {
            get {
                return ResourceManager.GetString("srl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        public static string srp {
            get {
                return ResourceManager.GetString("srp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        public static string ssw {
            get {
                return ResourceManager.GetString("ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to su.
        /// </summary>
        public static string sun {
            get {
                return ResourceManager.GetString("sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sw.
        /// </summary>
        public static string swa {
            get {
                return ResourceManager.GetString("swa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv.
        /// </summary>
        public static string swe {
            get {
                return ResourceManager.GetString("swe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syr.
        /// </summary>
        public static string syr {
            get {
                return ResourceManager.GetString("syr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ty.
        /// </summary>
        public static string tah {
            get {
                return ResourceManager.GetString("tah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ta.
        /// </summary>
        public static string tam {
            get {
                return ResourceManager.GetString("tam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tt.
        /// </summary>
        public static string tat {
            get {
                return ResourceManager.GetString("tat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg.
        /// </summary>
        public static string tgk {
            get {
                return ResourceManager.GetString("tgk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tl.
        /// </summary>
        public static string tgl {
            get {
                return ResourceManager.GetString("tgl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string tha {
            get {
                return ResourceManager.GetString("tha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bo.
        /// </summary>
        public static string tib {
            get {
                return ResourceManager.GetString("tib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ti.
        /// </summary>
        public static string tir {
            get {
                return ResourceManager.GetString("tir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string ton {
            get {
                return ResourceManager.GetString("ton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tn.
        /// </summary>
        public static string tsn {
            get {
                return ResourceManager.GetString("tsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ts.
        /// </summary>
        public static string tso {
            get {
                return ResourceManager.GetString("tso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tk.
        /// </summary>
        public static string tuk {
            get {
                return ResourceManager.GetString("tuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string tur {
            get {
                return ResourceManager.GetString("tur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tw.
        /// </summary>
        public static string twi {
            get {
                return ResourceManager.GetString("twi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ug.
        /// </summary>
        public static string uig {
            get {
                return ResourceManager.GetString("uig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string ukr {
            get {
                return ResourceManager.GetString("ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ung.
        /// </summary>
        public static string ung {
            get {
                return ResourceManager.GetString("ung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ur.
        /// </summary>
        public static string urd {
            get {
                return ResourceManager.GetString("urd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uz.
        /// </summary>
        public static string uzb {
            get {
                return ResourceManager.GetString("uzb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve.
        /// </summary>
        public static string ven {
            get {
                return ResourceManager.GetString("ven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        public static string vie {
            get {
                return ResourceManager.GetString("vie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vo.
        /// </summary>
        public static string vol {
            get {
                return ResourceManager.GetString("vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cy.
        /// </summary>
        public static string wel {
            get {
                return ResourceManager.GetString("wel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wa.
        /// </summary>
        public static string wln {
            get {
                return ResourceManager.GetString("wln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wo.
        /// </summary>
        public static string wol {
            get {
                return ResourceManager.GetString("wol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xh.
        /// </summary>
        public static string xho {
            get {
                return ResourceManager.GetString("xho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yi.
        /// </summary>
        public static string yid {
            get {
                return ResourceManager.GetString("yid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo.
        /// </summary>
        public static string yor {
            get {
                return ResourceManager.GetString("yor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za.
        /// </summary>
        public static string zha {
            get {
                return ResourceManager.GetString("zha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zu.
        /// </summary>
        public static string zul {
            get {
                return ResourceManager.GetString("zul", resourceCulture);
            }
        }
    }
}
